tensorflow/tfjs-models

posenet/README.md, posenet/demos/camera.html, posenet/demos/camera.js, posenet/demos/coco.js, posenet/src/mobilenet.ts, posenet/src/posenet.ts, posenet/src/util.ts, posenet/src/util_test.ts
* Changed from using an input image resolution to an `imageScaleFactor`
This results in calculation a resolution that would satisfy both the imageScaleFactor and having its odd value be divisible by the output stride.
* Changed the parameter reverse to `flipHorizontal`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/6)
=> Posenet - scale factor

posenet/demos/camera.html, posenet/demos/camera.js
* Made camera demo responsive for mobile - by using media query device
width meta tag.
* For mobile devices, defaulting to use mobile net multiplier 0.50
* Selecting camera using the modern api.  raising an error  if that api
doesn't exist on that browser
* Fixed mirroring of output image on ios.
* Got rid of gui for safari mobile since it clogs up the view . Just defaulting to single pose. Hiding the footer text on responsive mobile since it describes options that are no longer visible.
* Got rid of being able to switch camera since when using rear facing camera the mirroring is missed up.  In the future, will add that back in when we can fix the mirroring issues for rear facing camera.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Fixed camera demo for IOS safari

mobilenet/README.md
The CDN url for `https://cdn.jsdelivr.net/npm/@tensorflow-models/mobilenet@0.1.0` should be `@0.0.1`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/14)
=> Fix `@tensorflow-models` CDN url

mobilenet/package.json, mobilenet/yarn.lock, posenet/package.json, posenet/yarn.lock
Equivalent to tensorflow/tfjs-converter#149. The warning "@tensorflow/tfjs > @tensorflow/tfjs-converter@0.4.1" has incorrect peer dependency "@tensorflow/tfjs-core@0.11.3" should go away when tfjs-converter 0.4.2 is released with the mentioned PR.
Fixes tensorflow/tfjs#414.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/27)
=> Relax dependency version.

knn-classifier/.npmignore, knn-classifier/demo/camera.js, knn-classifier/demo/package.json, knn-classifier/demo/yarn.lock, knn-classifier/package.json, knn-classifier/yarn.lock, mobilenet/package.json, mobilenet/yarn.lock, posenet/package.json, posenet/yarn.lock
- The postinstall script `yarn upgrade` causes problems, especially for users that don't have yarn installed globally. Remove it
- Update the knn-classifier demo to use `onclick` instead of `mousedown/up` so that it works for both desktop and phones.
- Add `demo/` to `.npmignore` in knn-classifier
- Build the demo in knn-classifier as part of the travis presubmit
- Update dependencies to latest tfjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/47)
=> Remove postinstall script from models that we publish on npm

knn-classifier/demo/package.json, knn-classifier/demo/yarn.lock
add cross-env otherwise user may got "NODE_ENV is not recognized as an internal or external command" when run yarn watch on windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/65)
=> add cross-env for knn-classifier demo project

knn-classifier/src/index.ts, knn-classifier/src/index_test.ts
Fix typo in the KNNClassifier,
`s/exaples/examples/g`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/67)
=> Fix typo in the KNNClassifier

speech-commands/README.md, speech-commands/demo/index.html, speech-commands/demo/package.json, speech-commands/demo/yarn.lock, speech-commands/make-version, speech-commands/package.json, speech-commands/rollup.config.js, speech-commands/src/browser_fft_recognizer.ts, speech-commands/src/index.ts, speech-commands/src/index_test.ts, speech-commands/src/types.ts, speech-commands/src/version.ts, speech-commands/tsconfig.json, speech-commands/yarn.lock
Also in this PR:
* Add make-version script for automatic edits to version.ts
* Add unit test for exposed version string in the public API.
* In demo, increase the default number of training epochs for transfer learning from 20 to 40 (based on empirical observation of the transfer-learning accuracy)
* In the example in README.md, reflect the fact that @tensorflow/tfjs is a peer dependency.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/71)
=> [speech-commands]  Add versioning and release infra 

coco-ssd/demo/index.js, coco-ssd/demo/package.json, coco-ssd/demo/yarn.lock, coco-ssd/rollup.config.js
Was trying out the coco-ssd model and found a few issues.
The output variable name in the rollup config file should be changed from coco-ssd to cocoSsd to both avoid dashes in variable names and also to match the readme sample usage (for script tag usage).
This PR also fixes the version listed for coco-ssd in the package.json and also switches the demo to import the npm package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/83)
=> Fix coco-ssd package name and demo version

coco-ssd/README.md, coco-ssd/demo/README.md
This will help users know how to use and modify the coco-ssd demo app.
Old object-detection references were changed to coco-ssd in the main model README as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/84)
=> Add a README to the coco-ssd demo app

posenet/README.md
Found a small typo in the example code of multiple poses outputs at the end of README.md. I believe it meant 'pose 3' , not 'pose 2'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/88)
=> fixed minor typo in POSENET output example

coco-ssd/src/version.ts
This file is missing for the coco-ssd version bump to 0.1.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/108)
=> add missing version.ts file for coco-ssd

body-pix/demos/package.json, coco-ssd/demo/package.json, speech-commands/demo/package.json
Without `cross-env NODE_ENV` was impossible to run the demos on windows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/112)
=> Added windows support for all demos

posenet/demos/README.md
If you try to run the current instructions on a fresh clone, `yarn watch` will fail. Adding a `yarn build` command fixes things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/146)
=> missing command in demo readme

body-pix/demos/README.md, body-pix/demos/index.html, body-pix/demos/package.json, body-pix/demos/yarn.lock, body-pix/package.json, body-pix/src/util.ts, body-pix/yarn.lock
- Update bodypix to depend on tfjs 0.15.1
- Fix deprecated API usage
- Update body pix to 0.1.1 and release 0.1.1
- Update demo and upload on GCS: https://storage.googleapis.com/tfjs-models/demos/body-pix/index.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/147)
=> Update bodypix to depend on tfjs 0.15.1

speech-commands/package.json, speech-commands/src/browser_fft_utils.ts, speech-commands/src/version.ts
The parcel issue is described at:
https://github.com/parcel-bundler/parcel/issues/2363
parcel doesn't like `fs.readFileSync`. This PR uses `fs.readFile` to work around that.
BUG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/149)
=> Fix a parcel build warning; Bump version to 0.2.5

toxicity/README.md, universal-sentence-encoder/README.md
I think including an installation note that mentions `tfjs` may prevent potential confusion since it is a peer dependency of our models.
Also the new language models depend on `tfjs@1.0.0-alpha` so I updated the script tag `src` attribute mentioned in the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/153)
=> Add instructions to readme that indicates how to install peer dependencies, also specify the correct standalone script tags

toxicity/.npmignore, toxicity/package.json, universal-sentence-encoder/.npmignore, universal-sentence-encoder/package.json
The contents of my local ./cache directory were being uploaded to NPM which causes packages to exceed the size limit. 
Also bumped the version number so it would be possible to republish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/154)
=> Add cache directory to npmignore

speech-commands/package.json, speech-commands/src/browser_fft_recognizer.ts, speech-commands/src/browser_fft_recognizer_test.ts, speech-commands/src/index.ts, speech-commands/src/types.ts, speech-commands/src/version.ts
- Add method getMetadata() to transfer recognizer.
- Add the supporting interface.
- Bump version: 0.2.5 --> 0.2.6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/155)
=> [speech-commands] Add method getMetadata(); Bump version

body-pix/demos/yarn.lock
Fixed by running `yarn audit` followed by `yarn upgrade PCK_NAME` where PCK_NAME had `lodash` (the vulnerable package) as a dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/157)
=> Fix security vulnerability of our dev deps

body-pix/README.md, body-pix/demos/package.json, body-pix/demos/yarn.lock, body-pix/package.json, body-pix/src/body_pix_model.ts, body-pix/src/mobilenet.ts, body-pix/yarn.lock, coco-ssd/demo/package.json, coco-ssd/demo/yarn.lock, coco-ssd/package.json, coco-ssd/yarn.lock, knn-classifier/README.md, knn-classifier/demo/package.json, knn-classifier/demo/yarn.lock, knn-classifier/package.json, knn-classifier/yarn.lock, posenet/README.md, posenet/demos/package.json, posenet/demos/yarn.lock, posenet/package.json, posenet/src/mobilenet.ts, posenet/src/posenet_model.ts, posenet/yarn.lock
Also updates demos to depend on un-yet unpublished demos. So this should probably be merged after new model versions are published.
Models updated are: bodypix, cocossd, knn-classifier, posenet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/168)
=> Update models to depend on tfjs 1.0

speech-commands/demo/package.json, speech-commands/demo/yarn.lock, speech-commands/package.json, speech-commands/src/browser_fft_recognizer.ts, speech-commands/yarn.lock, test_util.ts
- General unit-test infrastructure fix:
- Let test_util.ts pick up only files in the respective `src/` directories of the models
- speech-commands
- Upgrade to tfjs and tfjs-node 1.0.2
- Name the dense layer of the new head explicitly
- Add NODE_OPTIONS to cross-env to prevent out-of-heap-memory error during `yarn watch` and `yarn build`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/176)
=> Various fixes to unit-test infra and speech-commands

knn-classifier/README.md, knn-classifier/package.json, knn-classifier/src/index.ts, knn-classifier/src/index_test.ts
Fixes https://github.com/tensorflow/tfjs/issues/1478
Users can now pass arbitrary classId/label when calling `addExample()`. The classId/label can be an arbitrary string or number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/188)
=> Allow users of knn to use arbitrary class Id

speech-commands/demo/dataset-vis.js, speech-commands/demo/index.html, speech-commands/demo/index.js, speech-commands/demo/style.css, speech-commands/src/browser_fft_extractor.ts, speech-commands/src/browser_fft_recognizer.ts, speech-commands/src/browser_fft_recognizer_test.ts, speech-commands/src/browser_fft_utils.ts, speech-commands/src/browser_test_utils.ts, speech-commands/src/dataset_test.ts, speech-commands/src/index.ts, speech-commands/src/types.ts
... in addition to spectrograms.
- The option argument to `collectExample()` now has a new field called
"includeTimeDomainWaveform". If set to true, the collected example
will include the raw audio waveform. Obviously, use caution when using
this feature as it'll increase the memory consumption of the examples
by a few times.
- The demo page now has a new checkbox called "Include audio waveform"
that demonstrates this new feature, along with the playback of the audio
waveforms through WebAudio.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/195)
=> [speech-commands] Add option to collect raw audio waveform during collectExample()

body-pix/.npmignore, coco-ssd/.npmignore, coco-ssd/package.json, knn-classifier/.npmignore, mobilenet/.npmignore, posenet/.npmignore, speech-commands/.npmignore, toxicity/.npmignore, universal-sentence-encoder/.npmignore
Add `.yalc` to `.npmignore` and update the version of coco-ssd so we can republish.
We published coco-ssd with `.yalc` which contains `node_modules`, making the package size exceed 50mb. This results in jsdelivr failing to serve our bundles with the error `Package size exceeded the configured limit of 50 MB.`
: https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd
I verified that all the other models are working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/203)
=> Ignore `.yalc/` folder when we publish to npm

universal-sentence-encoder/README.md
Corrected the language for an HTML code block in `universal-sentence-encoder/README.md`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/206)
=> Correct a code block language

posenet/src/checkpoint_loader.ts
replaced the XMLHttpRequest call for loading checkpoints with fetch.
The main reason is on some of the platform (i.e. wechat) XMLHttpRequest is not available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/204)
=> replace XMLHttpRequest with tfjs-core util fetch

posenet/demos/camera.js, posenet/demos/coco.js, posenet/demos/demo_util.js
The ResNet50 model will be triggered only when a user click the "Try ResNet50" button
* Adds a button to coco.js
* Adds a button to camera.js
* Switches default model to MobileNet for both image and camera demo
TODOs:
* adds a progress bar when downloading the ResNet weights
* exposes 'quantBytes' in the UI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/214)
=> Adds a button to trigger ResNet50 based PoseNet

posenet/README.md, posenet/demos/camera.js, posenet/demos/coco.js, posenet/src/checkpoints.ts, posenet/src/posenet_model.ts, posenet/src/single_pose/argmax2d_test.ts
This last PR concludes the ResNet50 model integration for PoseNet. We exposes the `quantBytes` to the users, so they can choose the right quantization level for their own usecase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/218)
=> Exposes `quantBytes` option for ResNet50 demos

posenet/package.json, posenet/src/checkpoint_loader.ts, posenet/src/mobilenet.ts, posenet/src/model_weights.ts, posenet/src/posenet_model.ts, posenet/src/posenet_test.ts, posenet/src/resnet.ts, posenet/src/single_pose/argmax2d.ts, posenet/src/single_pose/argmax2d_test.ts, posenet/src/single_pose/decode_single_pose.ts, posenet/src/single_pose/util.ts, posenet/src/types.ts, posenet/src/util.ts, posenet/yarn.lock
Since the code does not require tfjs-layers or tfjs-data, depending on tfjs union package, would
increase the user binary if they don't need layers or data either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/233)
=> narrow the dep to be core and converter only, and clean up the lint errors

posenet/demos/package.json, posenet/demos/yarn.lock, posenet/package.json, posenet/rollup.config.js
- Update Posenet version to 2.0
- Fix rollup config to exclude core and converter from the bundle
- Update demo to depend on Posenet 2.0
- Release new version of Posenet and demo on GCS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/234)
=> Update Posenet to 2.0

posenet/src/posenet_model.ts
The buffer variables are only necessary for multi-person decoding method and it's also not used for after decoding processing. So it can be self contained on the multi-person block and avoiding this processing for single-pose decoding operation.
On my local tests using the new 2.0 posenet version it's about 15% fps improvement for single pose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/230)
=> skip unneeded operation for posenet single-pose

body-pix/demos/.babelrc, body-pix/demos/package.json, body-pix/demos/yarn.lock, coco-ssd/demo/.babelrc, coco-ssd/demo/package.json, knn-classifier/demo/.babelrc, knn-classifier/demo/package.json, posenet/demos/.babelrc, posenet/demos/package.json, posenet/demos/yarn.lock, posenet/yarn.lock, speech-commands/demo/package.json, toxicity/demo/.babelrc, toxicity/demo/package.json, toxicity/demo/yarn.lock, toxicity/yarn.lock, universal-sentence-encoder/demo/.babelrc, universal-sentence-encoder/demo/index.js, universal-sentence-encoder/demo/package.json, universal-sentence-encoder/demo/yarn.lock, universal-sentence-encoder/yarn.lock
- Remove `--no-minify` from parcel and ignore require("crypto") . Leads to 2x reduction in js bundle size
- Remove polyfills (leads to further %5 reduction) and reduces third-party code in our bundle.
For example, the PoseNet demo went from 1.95MB to 960KB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/247)
=> Optimize the bundle of our demos

body-pix/package.json, body-pix/rollup.config.js, body-pix/yarn.lock, coco-ssd/package.json, coco-ssd/rollup.config.js, coco-ssd/yarn.lock, knn-classifier/demo/package.json, knn-classifier/demo/yarn.lock, knn-classifier/package.json, knn-classifier/rollup.config.js, knn-classifier/yarn.lock, mobilenet/package.json, mobilenet/rollup.config.js, mobilenet/yarn.lock, posenet/rollup.config.js, toxicity/demo/index.html, toxicity/demo/package.json, toxicity/demo/yarn.lock, toxicity/package.json, toxicity/rollup.config.js, toxicity/yarn.lock, universal-sentence-encoder/demo/package.json, universal-sentence-encoder/demo/yarn.lock, universal-sentence-encoder/package.json, universal-sentence-encoder/rollup.config.js
#237, #243 & #233 updated the peer dependencies of our models to be core and converter instead of the union.
However since the rollup config was not updated, this resulted in published model's bundles to include the whole tfjs-core and tfjs-converter. E.g. https://unpkg.com/@tensorflow-models/coco-ssd@1.1.0/dist/coco-ssd.min.js is ~577KB but should be ~27KB.
After this change, I will re-release patch versions of the updated models.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/250)
=> Fix rollup bundles and update versions

body-pix/src/body_pix_model.ts, body-pix/src/util.ts
In many of my personal projects I find myself wanting to work with the tensors returned from bodypix, instead of the cpu based output.    This is particularly the case when wanting to do shader based ops on the outputs.
This PR exposes tensor based ops on the `BodyPix` class.
The two new API methods are:
`estimatePersonSegmentationOp`
`estimatePartSegmentationOp`
They both take 3d tensors as inputs and return 2d tensors.
The existing API methods are unchanged.  They wrap the new api methods and convert the output to be cpu based arrays.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/275)
=> exposing body-pix tensor based ops

mobilenet/package.json, mobilenet/scripts/publish-npm.sh
published mobilenet 2.0.2 (https://registry.npmjs.org/@tensorflow-models/mobilenet/-/mobilenet-2.0.2.tgz) is missing some files. This PR would bump the version for a re-publish. We would then deprecate that version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/281)
=> bump mobilenet version

universal-sentence-encoder/src/tokenizer/trie.ts, universal-sentence-encoder/src/trie_test.ts
This removes recursive branching and caches array creation.  
```
import {loadTokenizer} from './index'
loadTokenizer().then(tokenizer => {
var gettysburg = 'Fourscore and seven years ago our fathers brought forth, on this continent, a new nation, conceived in liberty, and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived, and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting-place for those who here gave their lives, that that nation might live. It is altogether fitting and proper that we should do this. But, in a larger sense, we cannot dedicate, we cannot consecrate—we cannot …
```
=> simplifies and speeds up USE trie

body-pix/src/body_pix_model.ts
This should fix the following bug:
https://github.com/tensorflow/tfjs/issues/2182
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/307)
=> set default stride for MobileNet backbone to 16

body-pix/cloudbuild.yml, cloudbuild.yml, coco-ssd/cloudbuild.yml, deeplab/cloudbuild.yml, knn-classifier/cloudbuild.yml, mobilenet/cloudbuild.yml, posenet/cloudbuild.yml, presubmit.ts, scripts/run-build.sh, speech-commands/cloudbuild.yml, toxicity/cloudbuild.yml, universal-sentence-encoder/cloudbuild.yml
This mirrors the monorepo.
No functional changes except parallelizing the build and only running the subset of tests necessary.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/331)
=> Add cloud build scripts to run individual cloudbuild.yml's

body-pix/package.json, coco-ssd/package.json, deeplab/README.md, deeplab/demo/package.json, deeplab/demo/src/index.html, deeplab/package.json, deeplab/src/config.ts, deeplab/src/deeplab_test.ts, deeplab/src/index.ts, deeplab/src/utils.ts, deeplab/yarn.lock, knn-classifier/package.json, mobilenet/package.json, package.json, posenet/package.json, presubmit.ts, toxicity/package.json, universal-sentence-encoder/package.json
Updates the deeplab model urls to point to new tfhub hosted assets. 
Also cleans up some warnings to match new tslint settings.
Note after this PR lands:
- We will publish deeplab package to NPM (version is currently 0.1.0)
- Make a followup PR updating the package.json in the deeplab demo to point to newly published package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/342)
=> Update deeplab model urls

deeplab/README.md
1. Fixes the relative urls (path starts from the current directory instead of root)
2. Changes the lines number to jump to labels instead of color maps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/349)
=> Fix datasets urls in deeplab README

body-pix/src/body_pix_model.ts, body-pix/src/body_pix_test.ts
To support invoking .segmentPerson,MultiPerson,PersonParts,MultiPersonParts with an {} InferenceConfig, this PR marks the following fields in InferenceConfig optional:
* flipHorizontal
* internalResolution
* segmentationThreshold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/351)
=> marks flipHorizontal, internalResolution, segmentationThreshold optional

toxicity/demo/package.json, toxicity/demo/yarn.lock, toxicity/package.json, toxicity/src/index.ts, toxicity/src/version.ts, toxicity/yarn.lock, universal-sentence-encoder/demo/package.json, universal-sentence-encoder/demo/yarn.lock, universal-sentence-encoder/package.json, universal-sentence-encoder/src/index.ts, universal-sentence-encoder/src/version.ts
The lockfiles for the demos need to be updated after the modules are actually published.
I thought the workflow could be: once I get approval on this PR, I'll publish both USE and toxicity to NPM. Then I'll upgrade the yarn.lock files for both demos. Then I'll merge into master.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/381)
=> Actually use TFHub for USE and toxicity models.

toxicity/src/index.ts, universal-sentence-encoder/src/index.ts
Property renaming only happens with JSCompiler. Declare an interface for the properties will prevent JSCompiler renaming.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/391)
=> [Bug] Fix property renaming issue

blazeface/demo/index.js, blazeface/demo/package.json, blazeface/demo/yarn.lock, blazeface/package.json, blazeface/src/face.ts, blazeface/src/index.ts, blazeface/src/version.ts, blazeface/yarn.lock
Facemesh will depend on blazeface for bounding box detection. This PR makes it possible to fetch only the bounding boxes from blazeface without paying for other properties like facial landmarks.
Will update demo yarn.lock file after publishing blazeface, then will merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/397)
=> [blazeface] Enable getting bounding boxes only, export more types.

speech-commands/README.md
Little typo error in README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/409)
=> Fix typo speech-commands/README.md

body-pix/README.md
Fixes https://github.com/tensorflow/tfjs/issues/2844
As far as I can tell there is no 32 bit stride model.json for mobilenet based body pix in our storage bucket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/418)
=> Update body-pix strides documentation

handpose/demo/package.json, handpose/demo/yarn.lock, handpose/package.json, handpose/src/index.ts
I'll run `yarn` in the demo after publishing 0.0.3 of handpose to correct its lock file.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/419)
=> [handpose] Update asset URLs to use mediapipe

handpose/src/hand.ts, handpose/src/pipeline.ts
This paves the way for adding WebGPU support to handpose. 
Non-max suppression requires all inputs to reside in the CPU by calling `dataSync`, however synchronous read is not available in WebGPU. @axinging is working on a patch to handpose that asynchronously moves inputs to the CPU for NMS. Making `getBoundingBoxes` asynchronous unblocks his work. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/434)
=> [handpose] Make getBoundingBoxes async.

coco-ssd/package.json, coco-ssd/src/index.ts, coco-ssd/src/ssd_test.ts, coco-ssd/src/version.ts
The warm up tensor is not released, this would be problematic if the model is loaded multiple times.
fixes tensorflow/tfjs-wechat#56
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/440)
=> fix warm up tensor mem leak for coco-ssd

handpose/src/rotate_gpu.ts
It appears that sinFactor and cosFactor can be output into the shader as an integer (-1 or 1).  On iOS (13.4.1) safari this causes a shader compilation issue.  Every other browser I've tried has dealt with it just fine.
I'm not sure this is the best fix but I can confirm it does resolve the issue in iOS (13.4.1) safari.
Below is the relevant parts of the safari console log:
```
[Log] ERROR: 0:159: '*' : wrong operand types - no operation '*' exists that takes a left-hand operand of type 'highp float' and a right operand of type 'const int' (or there is no acceptable conversion)
int coordX = int(float(x - 424) * 6.123233995736766e-17 - float(y - 188) * -1);
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> iOS safari shader compilation issue

body-pix/src/util.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/523)
=> Bug fix: tfjs treats HTMLVideoElement as 0*0 size by default

toxicity/README.md
Update toxicity readme to import tfjs in the commonjs snippet. Without this you get no backend found error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/525)
=> update toxicity readme to import tfjs

posenet/rollup.config.js
Sourcemap flag enables the typescript symbol for debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/535)
=> Add sourcemap for posenet

coco-ssd/src/index.ts
fixes https://github.com/tensorflow/tfjs/issues/4234
The warning message is shown when redirect the post-processing to cpu backend, this should only be enabled for webgl backend, given that node and wasm backend would be faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/538)
=> redirect to cpu only for webgl backend

coco-ssd/package.json, coco-ssd/src/version.ts
ref https://github.com/tensorflow/tfjs/issues/4234
The warning message is shown when redirect the post-processing to cpu backend, this should only be enabled for webgl backend, given that node and wasm backend would be faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/540)
=> update coco-ssd to 2.2.0

coco-ssd/package.json, coco-ssd/src/version.ts
Somehow the published npm package failed to be loaded in the demo, republishing coco-ssd with a new version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/541)
=> bump version to 2.2.1

coco-ssd/rollup.config.js
This fixes the syntax error when loaded in the demo app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/542)
=> use umd for es2017 format

blazeface/demo/package.json, cloudbuild.yml, deeplab/cloudbuild.yml, deeplab/demo/README.md, deeplab/demo/package.json, deeplab/demo/src/index.js, deeplab/demo/yarn.lock, deeplab/package.json, deeplab/run_tests.ts, deeplab/src/deeplab_test.ts, deeplab/src/index.ts, deeplab/src/utils.ts, deeplab/yarn.lock
Upgrade deeplab to build against tfjs 3.0.0-rc-1
Fixes:
- Deeplab's tests weren't actually running in CI and it's own cloudbuild.yml was written to execute the wrong tests.
- Pre-upgrade the tests weren't working on recent versions of node due to a 'canvas' package dependency that doesn't work on recent version of node. That dependency was used in a single test that I don't think was that valuable so I removed that test.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/563)
=> upgrade deeplab to 3.0.0-rc.1

speech-commands/src/browser_fft_extractor.ts
Fix error: Mismatch in sampling rate: Expected: 44100; Actual: 48000
Browser now allows setting sampling rate. Fixes https://github.com/tensorflow/tfjs/issues/3845
It is available in Firefox: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext
And chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=432248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/612)
=> [speech-command]Fix sampleRate mismatch.

pose-detection/run_tests.ts, pose-detection/src/calculators/convert_image_to_tensor.ts, pose-detection/src/calculators/image_utils.ts, pose-detection/src/calculators/interfaces/common_interfaces.ts, pose-detection/src/calculators/interfaces/config_interfaces.ts, pose-detection/src/calculators/interfaces/shape_interfaces.ts, pose-detection/src/calculators/shift_image_value.ts, pose-detection/src/constants.ts, pose-detection/src/create_detector.ts, pose-detection/src/index.ts, pose-detection/src/pose_detector.ts, pose-detection/src/posenet/calculators/decode_single_pose.ts, pose-detection/src/posenet/calculators/decode_single_pose_util.ts, pose-detection/src/posenet/calculators/flip_poses.ts, pose-detection/src/posenet/calculators/scale_poses.ts, pose-detection/src/posenet/constants.ts, pose-detection/src/posenet/detector.ts, pose-detection/src/posenet/detector_utils.ts, pose-detection/src/posenet/load_utils.ts, pose-detection/src/posenet/posenet_test.ts, pose-detection/src/posenet/types.ts, pose-detection/src/types.ts
This PR includes below changes:
1. Add PoseNet single pose estimation.
2. Add convertImageToTensor, to be shared by all image processing models.
2. Setup test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/611)
=> [posedetection] PoseNet single pose migration

pose-detection/demo/src/camera.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/631)
=> [pose-detection]Update demo doccomment.

pose-detection/src/calculators/interfaces/config_interfaces.ts, pose-detection/src/calculators/low_pass_filter.ts, pose-detection/src/calculators/one_euro_filter.ts
The OneEuroFilter implementation doesn't handle non-Gaussian error well. Based on MoveNet's research, we can add another non-linear function to cap the extreme outliers.
In the original one euro method:
x(t) = alpha * x(t) + (1 - alpha) * x(t-1) = x(t-1) + alpha*(x(t) - x(t-1)), where alpha is calculated dynamically based on frequency. 
In the improved one euro method:
x(t) = x(t-1) + alpha * threshold * (x(t) - x(t-1)), where both alpha and threshold is calculated dynamically based on frequency. Alpha can be tuned by minCutOff and slope. Threshold can be tuned by thresholdCutOff and thresholdSlope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/632)
=> [pose-detection]Improve one euro filter and low pass filter.

pose-detection/src/blazepose/calculators/landmarks_smoothing.ts, pose-detection/src/blazepose/calculators/non_max_suppression.ts, pose-detection/src/blazepose/detector.ts, pose-detection/src/blazepose/detector_utils.ts, pose-detection/src/movenet/detector.ts, pose-detection/src/pose_detector.ts, pose-detection/src/posenet/detector.ts
Allow timestamp as a user input. This is useful when image input is an imageTensor, which doesn't have timestamp information. Or when we want to override the timestamp from the video.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/648)
=> [pose-detection]Allow timestamp as a user input.

pose-detection/demos/live_video/src/index.js
The demo fired too many requestAnimationFrame. This PR fixed it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/691)
=> [pose-detection]Fix demo issue.

pose-detection/src/blazepose_mediapipe/detector.ts, pose-detection/src/create_detector.ts
Waiting until the first frame to initialize the solution causes
some frames to drop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/712)
=> Initialize MediaPipe solution during create_detector.

pose-detection/src/blazepose_mediapipe/detector.ts, pose-detection/src/blazepose_mediapipe/mediapipe_test.ts, pose-detection/src/blazepose_tfjs/detector.ts, pose-detection/src/calculators/constants.ts, pose-detection/src/movenet/detector.ts, pose-detection/src/pose_detector.ts, pose-detection/src/test_util.ts
Change API's timestamp field unit to milliseconds, this is more common for web developers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/718)
=> [pose-detection]timestamp change unit to milliseconds.

pose-detection/src/blazepose_mediapipe/detector.ts
results.poseLandmarks could be null, fix the bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/726)
=> [pose-detection]Fix null case in BlazePose MediaPipe solution.

pose-detection/src/blazepose_mediapipe/detector.ts, pose-detection/src/blazepose_mediapipe/types.ts, pose-detection/src/blazepose_tfjs/detector.ts, pose-detection/src/blazepose_tfjs/types.ts, pose-detection/src/movenet/constants.ts, pose-detection/src/movenet/detector.ts, pose-detection/src/movenet/detector_utils.ts, pose-detection/src/movenet/types.ts, pose-detection/yarn.lock
BlazePose has already changed. This is to keep API consistency
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/727)
=> [pose-detection]Change enableSmoothing to modelConfig for MoveNet.

face-landmarks-detection/demo/README.md, face-landmarks-detection/demo/index.js, face-landmarks-detection/demo/package.json, face-landmarks-detection/demo/rollup.config.js, face-landmarks-detection/demo/scripts/build-demo.sh, face-landmarks-detection/demo/yarn.lock
This is related to tensorflow/tfjs#5137. This PR includes the following fixes:
- Fixed `ReferenceError: e is not defined` error. It was caused by `parcel` bundler's minification process which is not "compatible" with our WASM backend. The fix is to use rollup with the correct terser config (see [here](https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-wasm#js-minification) for more info).
- The backend switching in the demo was not working correctly. In addition to calling `cancelAnimationFrame`, we also need to stop the currently running callback before setting the new backend (`cancelAnimationFrame` will only cancel the scheduled callback). Without doing this, the "backend not ready" error will be thrown when switching to the WASM backend even if we are using `await …
=> Fix face landmark detection demo

coco-ssd/README.md
The current link redirects to a 404 page. This PR aims to redirect users to the new maintained README file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/755)
=> Update 404 Link for Coco Models

pose-detection/src/movenet/constants.ts
Version 4 of the MoveNet Lightning and Thunder models were recently
released on TF Hub:
https://tfhub.dev/google/movenet/singlepose/lightning/4
https://tfhub.dev/google/movenet/singlepose/thunder/4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/760)
=> [pose-detection] Update MoveNet models to v4

pose-detection/demos/live_video/src/index.js, pose-detection/demos/live_video/yarn.lock, pose-detection/yarn.lock
Fix https://github.com/tensorflow/tfjs/issues/5400
The current code depend on specific version of @mediapipe/pose, but the wasm file comes from the latest. It broke the demo today. The temporary fix in this PR is to pin the wasm file to the 0.3.x version. Long term solution is for @mediapipe/pose to export a version variable, so that we can always get a matched wasm file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/766)
=> [pose-detection]Fix demo.

knn-classifier/README.md
Fixes https://github.com/tensorflow/tfjs/issues/5250
As the embedding parameter in infer method is changed here https://github.com/tensorflow/tfjs-models/pull/161/files to boolean.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/823)
=> Update infer method

hand-detection/src/mediapipe/types.ts
This API will be used in the detector creation function as well as the estimateHands methods of the MediaPipe detector implementation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/834)
=> Add mediapipe API for hands

hand-detection/src/mediapipe/types.ts
Removing the minDetectionConfidence due to @lina128 pointing out that users shouldn't need it to reject hands, they can use keypoint score to do so, which is more accurate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/836)
=> Remove minDetectionConfidence from hands config

blazeface/demo/package.json, blazeface/demo/yarn.lock
#851 did not add esbuild to the demo's package.json. This PR adds it.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/852)
=> [blazeface] Add missing esbuild dependency

pose-detection/src/blazepose_mediapipe/README.md
Related to https://github.com/tensorflow/tfjs/issues/5501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/869)
=> Update blazepose-mediapipe README to make it clear that it doesn't support tfjs-react-native.

qna/src/question_and_answer.ts, qna/src/question_and_answer_test.ts
This commit has a small fix in the qna model function
getBestAnswers to protect the calls to convertBack so that it is
only called with indexes that can be found in tokenToOrigMap.
I needed to update the test to reflect the new behaviour.
Contributes to: tensorflow/tfjs#5946
Signed-off-by: Dale Lane <dale.lane@uk.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/888)
=> fix: improve check for accessing token map in qna model

face-landmarks-detection/package.json, face-landmarks-detection/src/tfjs/tfjs_test.ts, face-landmarks-detection/src/version.ts, shared/calculators/landmarks_refinement.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1035)
=> Fix face-landmarks-detection z value getting replaced

body-segmentation/src/selfie_segmentation_mediapipe/README.md, body-segmentation/src/selfie_segmentation_mediapipe/segmenter.ts, body-segmentation/src/selfie_segmentation_mediapipe/types.ts
What is better about this one is that it allows you to manage files directly in Bundler.
When combined with vite3, it looks like this
```typescript
import {
BodySegmenter,
SupportedModels,
createSegmenter 
} from '@tensorflow-models/body-segmentation'
const selfieSegmentationmodulesMap = async ()=> {
const modules = import.meta.glob('../../node_modules/@mediapipe/selfie_segmentation/*', { as: 'url' })
const ret:[string, string][] = []
for (const entry of Object.entries(modules)) {
ret.push([entry[0].split('/').pop() || '', await entry[1]()])
}
return Object.fromEntries(ret)
}
export const createMediapipeSegmenter = async (): Promise<BodySegmenter> => {
const modulesMap = await selfieSegmentationmodulesMap()
const model = SupportedModels.MediaPipeSelfieSegmentation
return …
```
=> Allow locateFile to be specified directly

hand-pose-detection/README.md
A link to an image on the hand-pose-detection documentation was broken. I updated it with a new url which matches the url of the original, except it's from 'mediapipe.dev' instead of 'google.github.io'.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1040)
=> updated broken image link in the hand-pose-detection documentation

blazeface/src/blazeface_test.ts, blazeface/src/face.ts
Hi tfjs team 👋!
This PR fixes two memory leaks in blazeface - hopefully this is helpful even though it's deprecated.
I can confirm (at least in terms of allocated tensors) that there aren't any more leaks.  I also removed an unnecessary null check from the previous PR that added the `dispose()` method.
Is there any chance these changes could be pushed to `npm`?  I'd be happy to switch to the new face detection engine but that detector doesn't return a probability / confidence AFAIK and this functionality is required for my work.
Thanks for all your work and your willingness to open source this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1038)
=> Fix blazeface memory leak

pose-detection/rollup.config.js
This fixes the duplicated kernel registration problem.
The production code will include code from other package when: package is imported(such as import * as tfwebgpu from '@tensorflow/tfjs-backend-webgpu';) and is non external in rollup.config.js.
Pose-detection will include a copy of tfjs-backend-webgpu.js(it is imported and is non external). E2e also loads tfjs-backend-webgpu.js with <script> tag. The two tfjs-backend-webgpu.js cannot be understood as the same package, so it will load twice.
Bug: https://github.com/tensorflow/tfjs/issues/7521
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1140)
=> Set webgl and webgpu as external

toxicity/README.md, toxicity/src/index.ts
In  the [readme](https://github.com/tensorflow/tfjs-models/tree/master/toxicity#usage) of Text-toxicity's example, for each category, there are two numbers indicating the probabilities of `false` and `true` for whether the input matches.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1142)
=> [Text-Toxicity] Fix description for model usage

tsconfig.json
Fixes an issue where the WebGPU backend is referencing types that are not available. @types/dom-webcodecs could be added to the WebGPU backend, but this could potentially cause conflicts as types from that package are added to lib/dom, e.g.:
```
node_modules/typescript/lib/lib.dom.d.ts:28200:6 - error TS2300: Duplicate identifier 'VideoPixelFormat'.
28200 type VideoPixelFormat = "BGRA" | "BGRX" | "I420" | "I420A" | "I422" | "I444" | "NV12" | "RGBA" | "RGBX";
~~~~~~~~~~~~~~~~
node_modules/@types/dom-webcodecs/webcodecs.generated.d.ts:416:6
416 type VideoPixelFormat = "BGRA" | "BGRX" | "I420" | "I420A" | "I422" | "I444" | "NV12" | "RGBA" | "RGBX";
~~~~~~~~~~~~~~~~
'VideoPixelFormat' was also declared here.
```
Consequently, I think it's best to just set `skipLibCheck` here.
=> Add 'skipLibCheck=true' to tsconfig

README.md
I've identified and addressed a broken link to the [speech commands dataset](https://www.tensorflow.org/tutorials/sequences/audio_recognition) within the tfjs-models [table](https://github.com/tensorflow/tfjs-models?tab=readme-ov-file#models) for [speech commands dataset](https://www.tensorflow.org/tutorials/sequences/audio_recognition) for the audio type speech commands model. I've replaced the non-functional link with this more relevant and current resource: https://www.tensorflow.org/tutorials/audio/simple_audio so either we can directly point to [speech commands dataset ](https://www.tensorflow.org/datasets/catalog/speech_commands) or replace with this link :https://www.tensorflow.org/tutorials/audio/simple_audio
Please review the change and provide any feedback or suggestions you may …
=> Update broken link for speech_commands dataset

universal-sentence-encoder/README.md
I've identified and addressed a broken link to [TensorFlow Hub USE lite colab](https://colab.sandbox.google.com/github/tensorflow/hub/blob/master/examples/colab/semantic_similarity_with_tf_hub_universal_encoder_lite.ipynb#scrollTo=_GSCW5QIBKVe) in this [page](https://github.com/tensorflow/tfjs-models/tree/master/universal-sentence-encoder#universal-sentence-encoder-lite) and I've replaced the non-functional link with this more relevant and current resource: https://github.com/tensorflow/docs/blob/master/site/en/hub/tutorials/semantic_similarity_with_tf_hub_universal_encoder_lite.ipynb
Please review the change and provide any feedback or suggestions you may have. If you agree with the update, please do the needful. Thank you.
=> Update broken link for TensorFlow Hub USE lite colab

face-detection/demos/shared/params.js, face-landmarks-detection/demos/shared/util.js, gpt2/src/index.ts, hand-pose-detection/demos/shared/params.js, hand-pose-detection/demos/shared/util.js, model-playground/README.md, pose-detection/demos/live_video/src/params.js, pose-detection/demos/upload_video/src/params.js, pose-detection/src/blazepose_tfjs/constants.ts, pose-detection/src/blazepose_tfjs/detector.ts, pose-detection/src/posenet/types.ts
Hi, Team
I've identified and corrected several typos within the documentation strings (code comments) of `.ts` files in the `tfjs-models` folder. I believe these corrections will improve the clarity and accuracy of the documentation for users. I appreciate your time and look forward to your feedback. Thank you.
=> Address typos in tfjs-models documentation string
