tensorflow/tfjs-models

posenet/package.json
posenet/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/8)

Update package.json of PoseNet to prepare for NPM publishing.

---

posenet/README.md
posenet/demos/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/9)

Add a demo link and script to build just the camera demo.

---

posenet/README.md
posenet/demos/README.md
posenet/demos/camera.js
posenet/demos/coco.js
posenet/demos/demo_util.js

- Fixed absolute link for the GIF in the main README. Wasn't showing up on npm. 
- Added a few comments to the demo javascript code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/11)

Improving documentation in the README and demos

---

posenet/demos/camera.js
posenet/demos/coco.html
posenet/demos/demo_util.js

Switching back to 2 spaces
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/12)

fixed tabbing

---

posenet/demos/coco.js

I removed the "detectPoseButton" from Gui.dat and automated "outputStride" and "image" to work directly. 
I was going to get "resolution" or "imageScaleFactor" working with this pull request but that will be a bit more complex set of changes. Would like to separate things into two pull requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/18)

Remove detectPoseButton 

---

posenet/.gitignore
posenet/package.json
posenet/rollup.config.js
posenet/tsconfig.json
posenet/yarn.lock

This PR switches from Browserify to Rollup, producing a UMD bundle with a dependency on `@tensorflow/tfjs`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/15)

Switch to Rollup.

---

posenet/demos/camera.html
posenet/demos/camera.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/21)

Alert user when getUserMedia throws an error

---

posenet/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/22)

Add link to issues to readme

---

posenet/README.md
posenet/src/posenet.ts

Added documentation for the alternate models, explaining how to load them and the effect of the multiplier values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/24)

documented alternate PoseNet models

---

mobilenet/package.json
mobilenet/yarn.lock
posenet/.npmignore
posenet/demos/README.md
posenet/demos/camera.js
posenet/demos/coco.js
posenet/demos/demo_util.js
posenet/demos/package.json
posenet/demos/yarn.lock
posenet/package.json
posenet/yarn.lock

- Update posenet and mobilenet model to depend on latest tfjs
- Update posenet demo to depend on the public posenet npm package
- Release new posenet (0.1.1)
Fixes https://github.com/tensorflow/tfjs/issues/323
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/26)

Update posenet model and demo

---

posenet/demos/README.md

Updated demos readme to show how to develop posenet locally with the demos.
Changes are a result of PR #26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/28)

Updates to demos README.md for posenet local development.

---

.travis.yml
package.json
posenet/.travis.yml
posenet/package.json
posenet/src/checkpoints.ts
posenet/src/index.ts
posenet/src/mobilenet.ts
posenet/src/multiPose/decodeMultiplePoses.ts
posenet/src/posenet.ts
posenet/src/posenet_test.ts
posenet/src/singlePose/argmax2d.ts
posenet/src/singlePose/decodeSinglePose.ts
posenet/src/singlePose/util.ts
posenet/src/util.ts
posenet/src/util_test.ts
posenet/tslint.json

Added travis config and fixed linting errors. As part of this had to remove some default exports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/25)

Added travis config to PoseNet, and fixed linting errors.

---

posenet/demos/package.json
posenet/demos/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/32)

Update posenet demos to point to 0.1.2.

---

knn-classifier/package.json
knn-classifier/src/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/37)

Use Number.isInteger when checking the classId in the knn classifier.

---

README.md
knn-classifier/README.md
mobilenet/README.md
posenet/README.md

- remove unkpg links and add links to jsDelivr.
- add es5 instructions for knn classifier.
- add knn classifier to readme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/39)

Add links to jsDelivr.

---

knn-classifier/demo/camera.js
knn-classifier/rollup.config.js
mobilenet/rollup.config.js
posenet/demos/camera.js
posenet/demos/coco.js
posenet/demos/demo_util.js
posenet/rollup.config.js
posenet/src/checkpoints.ts
posenet/src/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/41)

Fix broken license link

---

knn-classifier/README.md

Updated variable names and wrapped it in an async function
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/45)

Fixed script tag example

---

posenet/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/48)

Small typo on "or" in Readme

---

knn-classifier/demo/README.md
knn-classifier/demo/package.json
knn-classifier/demo/yarn.lock
knn-classifier/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/49)

Fix the local development steps for KNN classifier.

---

speech-commands/package.json
speech-commands/src/types.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/52)

add the recognizer interface

---

knn-classifier/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/56)

fix knn-classifier/README.md minor typo

---

posenet/demos/camera.js
posenet/demos/coco.js
posenet/demos/demo_util.js

Added a checkbox to render the boundingbox for the coco and camera demo.
Here is a screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/57)

Added boundingbox checkbox to demos

---

speech-commands/README.md
speech-commands/demo/index.html
speech-commands/demo/index.js
speech-commands/demo/ui.js
speech-commands/src/browser_fft_extractor.ts
speech-commands/src/browser_fft_extractor_test.ts
speech-commands/src/browser_fft_recognizer.ts
speech-commands/src/browser_fft_recognizer_test.ts
speech-commands/src/index.ts
speech-commands/src/types.ts

- Add logic for suppression and optional parameter `suppressionTimeMillis`
- Add logic for ignoring `_background_noise_` and `_unknown_` tokens
- Add optional parameter `invokeCallbackOnNoiseAndUnknown`
- Switch to model that includes unknown tokens
- Update README
- Respond to @dsmilkov 's comments on an earlier PR
- demo page: Add highlighting of the word with top score
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/61)

speech-commands: Add logic for suppression; Improve demo and README

---

knn-classifier/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/68)

knn-classifier README: update bundle version

---

speech-commands/demo/index.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/70)

speech-commands: fix typo in demo index.html

---

posenet/yarn.lock

package.json updated in a previous PR.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/76)

Update yarn.lock for PoseNet.

---

posenet/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/77)

Update posenet version to 0.2.3.

---

coco-ssd/demo/package.json
coco-ssd/demo/yarn.lock

since the coco-ssd npm is published, update the package.json to deps on the latest version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/81)

udpate coco-ssd model demo deps

---

posenet/src/posenet_model.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/80)

Fix typo in documentation

---

posenet/README.md

Removed duplicate declaration,
```
const outputStride = 16;
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/82)

Duplicate declaration, "const outputStride = 16;"

---

coco-ssd/demo/package.json
coco-ssd/demo/yarn.lock
coco-ssd/yarn.lock
knn-classifier/demo/package.json
knn-classifier/demo/yarn.lock
knn-classifier/yarn.lock
mobilenet/yarn.lock
posenet/demos/package.json
posenet/demos/yarn.lock
posenet/yarn.lock
speech-commands/demo/package.json
speech-commands/demo/yarn.lock
speech-commands/yarn.lock
yarn.lock

Also uses new version of yarn, adding the integrity bit.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/89)

Update parcel-bundler to 0.10.3.

---

README.md
coco-ssd/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/95)

Document coco SSD and speech commands from the root readme.

---

speech-commands/README.md
speech-commands/demo/index.js
speech-commands/package.json
speech-commands/src/browser_fft_recognizer.ts
speech-commands/src/browser_fft_recognizer_test.ts
speech-commands/src/types.ts
speech-commands/src/version.ts

- startStreaming() --> listen()
- stopStreaming() --> stopListening()
- isStreaming() --> isListening()
- Update model location
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/100)

[speech-commands] Changes to API and model location

---

speech-commands/package.json
speech-commands/src/browser_fft_recognizer.ts
speech-commands/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/103)

[speech-commands] Load embedding layer only for includeEmbedding=true

---

speech-commands/README.md

Fixes https://github.com/tensorflow/tfjs/issues/950
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/114)

[speech-commands] Fix a typo in README.md

---

body-pix/README.md
body-pix/demos/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/115)

Update readme of body pix to point to the correct demo URL.

---

posenet/demos/coco.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/102)

Fix <canvas> HTML tag

---

speech-commands/demo/index.js
speech-commands/demo/ui.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/117)

[speech-commands] Let highlighting for recognized word fade after a TTL

---

speech-commands/demo/package.json
speech-commands/package.json
speech-commands/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/122)

[speech-commands] Upgrade tensorflow.js and tfjs-node to latest releases

---

speech-commands/src/browser_fft_utils.ts
speech-commands/src/dataset.ts
speech-commands/src/dataset_test.ts
speech-commands/training/browser-fft/train.ts
speech-commands/training/browser-fft/train_test.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/127)

[speech-command] Check in responses to review comments from #126

---

speech-commands/README.md
speech-commands/package.json
speech-commands/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/128)

[speech-command] Bump version to 0.2.3; Add demo link to README

---

body-pix/src/util.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/129)

[body-pix] fixed resizing and padding of pictures narrower than the input image size

---

speech-commands/demo/dataset-vis.js
speech-commands/demo/index.html
speech-commands/demo/package.json
speech-commands/demo/ui.js
speech-commands/demo/yarn.lock
speech-commands/package.json
speech-commands/src/browser_fft_recognizer.ts
speech-commands/src/browser_fft_recognizer_test.ts
speech-commands/src/dataset.ts
speech-commands/src/dataset_test.ts
speech-commands/src/types.ts
speech-commands/yarn.lock

in a long spectrogram (i.e., a spectrogram with a frame count
greater than what's accepted by the convnet model)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/134)

[speech-commands] Allow manual specification of key frame index

---

body-pix/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/142)

[Body-Pix] - Fix tfjs import version in readme

---

universal-sentence-encoder/.npmignore
universal-sentence-encoder/README.md
universal-sentence-encoder/rollup.config.js
universal-sentence-encoder/yarn.lock

- Rename the global variable to `use`
- Add `.npmignore` file to reduce npm pkg size
- Update the docs to reflect both npm and script tag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/144)

Prepare universal sentence encoder for npm

---

universal-sentence-encoder/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/151)

Bump version of USE to 0.0.2

---

body-pix/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/152)

body-pix - Fix bokeh demo link

---

toxicity/src/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/159)

Bump toxicity prediction threshold to 0.85 per team recommendation.

---

toxicity/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/160)

Bump toxicity 0.2 --> 0.1.0

---

speech-commands/package.json
speech-commands/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/163)

Add publish command to speech-commands and bump version to enable publishing.

---

mobilenet/demo/index.html
mobilenet/package.json
mobilenet/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/166)

Depend on tfjs1.0 in mobilenet.

---

universal-sentence-encoder/README.md
universal-sentence-encoder/demo/package.json
universal-sentence-encoder/demo/yarn.lock
universal-sentence-encoder/package.json
universal-sentence-encoder/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/164)

Depend on tfjs 1.0 in USE. 

---

toxicity/README.md
toxicity/demo/package.json
toxicity/demo/yarn.lock
toxicity/package.json
toxicity/src/index.ts
toxicity/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/165)

Depend on tfjs1.0 in toxicity.

---

speech-commands/demo/package.json
speech-commands/package.json
speech-commands/src/browser_fft_extractor.ts
speech-commands/src/browser_fft_recognizer.ts
speech-commands/src/browser_fft_recognizer_test.ts
speech-commands/src/dataset.ts
speech-commands/src/dataset_test.ts
speech-commands/src/index.ts
speech-commands/src/training_utils.ts
speech-commands/src/version.ts
speech-commands/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/167)

Depend on tfjs 1.0 in speech commands.

---

mobilenet/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/174)

Update versions of tfjs and mobilenet in the example code

---

speech-commands/package.json
speech-commands/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/180)

[speech-commands] Bump version: 0.3.0 --> 0.3.1

---

body-pix/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/183)

Fix typo in source code

---

speech-commands/package.json
speech-commands/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/181)

[speech-commands] Bump version: 0.3.1 --> 0.3.2

---

speech-commands/package.json
speech-commands/src/version.ts

increase speech commands version to 0.3.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/184)

increase speech commands version to 0.3.3

---

speech-commands/package.json
speech-commands/src/browser_fft_recognizer.ts
speech-commands/src/browser_fft_recognizer_test.ts
speech-commands/src/browser_fft_utils.ts
speech-commands/src/version.ts

BUG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/185)

[speech-commands] Fix incorrect metadata field for word labels; v0.3.4

---

speech-commands/README.md
speech-commands/src/browser_fft_recognizer.ts
speech-commands/src/browser_fft_recognizer_test.ts
speech-commands/src/dataset.ts
speech-commands/src/dataset_test.ts
speech-commands/src/types.ts

- To this end, add wordLabels arg to Dataset.serialize()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/190)

[speech-commands] Add wordLabels arg to serializeExamples()

---

speech-commands/demo/index.html
speech-commands/demo/index.js
speech-commands/demo/style.css
speech-commands/src/browser_fft_recognizer.ts
speech-commands/src/browser_fft_recognizer_test.ts
speech-commands/src/dataset.ts
speech-commands/src/dataset_test.ts
speech-commands/src/generic_utils.ts
speech-commands/src/index.ts
speech-commands/src/types.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/186)

[speech-commands] Audio data augmentation: augumentByMixingNoiseRatio

---

speech-commands/package.json
speech-commands/src/version.ts
speech-commands/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/191)

[speech-commands] Bump version: 0.3.4 --> 0.3.5

---

body-pix/demos/package.json
body-pix/demos/yarn.lock
body-pix/package.json
coco-ssd/demo/package.json
coco-ssd/demo/yarn.lock
coco-ssd/package.json
knn-classifier/demo/package.json
knn-classifier/demo/yarn.lock
knn-classifier/package.json
mobilenet/package.json
posenet/demos/package.json
posenet/demos/yarn.lock
posenet/package.json
toxicity/demo/package.json
toxicity/demo/yarn.lock
toxicity/package.json
toxicity/yarn.lock
universal-sentence-encoder/demo/package.json
universal-sentence-encoder/demo/yarn.lock
universal-sentence-encoder/package.json

Update and release versions of all models (except speech-commands)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/194)

Update and release versions of all models (except speech-commands)

---

universal-sentence-encoder/package.json
universal-sentence-encoder/src/index.ts

Use `tf.util.fetch` in the USE.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/196)

Use tf.util.fetch in USE.

---

toxicity/package.json
toxicity/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/197)

Update toxicity dependency on USE.

---

speech-commands/package.json
speech-commands/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/201)

[speech-commands] Bump version: 0.3.5 --> 0.3.6

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/200)

Update README.md: Mention text models

---

toxicity/README.md

Corrected the language for an HTML code block in `toxicity/README.md`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/205)

Correct a code block language

---

posenet/package.json

Increase the posenet model to 1.0.3 to include the removal of HttpXMLRequest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/207)

increase the version to 1.0.3

---

speech-commands/package.json
speech-commands/src/browser_fft_extractor_test.ts
speech-commands/src/browser_fft_utils_test.ts
speech-commands/src/dataset_test.ts
speech-commands/src/test_utils.ts
speech-commands/src/training_utils_test.ts
speech-commands/src/version.ts
speech-commands/yarn.lock

- Upgrade to tfjs 1.1.2
- Fix breakages due to breaking changes in the test methods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/211)

[speech-commands] Bump version to 0.3.7

---

speech-commands/package.json
speech-commands/src/version.ts
speech-commands/tsconfig.json

- Remove extraneous run_tests.ts from tsconfig include
- The file was added to tsconfig in https://github.com/tensorflow/tfjs-models/pull/193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/215)

[speech-commands] Fix build

---

toxicity/README.md
universal-sentence-encoder/README.md

This PR fixes https://github.com/tensorflow/tfjs/issues/1618
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/219)

Update docs for USE / toxicity.

---

posenet/README.md

Closes https://github.com/tensorflow/tfjs/issues/1608
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/220)

Update posenet readme to refer to npm

---

posenet/src/checkpoints.ts
posenet/src/posenet_model.ts

This allow user to load the model from mirrors in China.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/209)

allow weight to be loaded from custom url

---

mobilenet/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/224)

Update return value info for mobilenet.classify

---

body-pix/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/223)

word spell mistake

---

posenet/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/239)

Updates README.md

---

speech-commands/package.json
speech-commands/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/240)

[speech-commands] Bump version to 0.3.9

---

toxicity/demo/package.json
toxicity/package.json
toxicity/src/index.ts
toxicity/yarn.lock

removed peer deps for tfjs union package, and add tfjs-core and tfjs-converter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/243)

update peer deps for toxicity model and increase the minor version

---

posenet/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/244)

Update posenet lock file.

---

posenet/README.md

Fix the broken gif in PoseNet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/246)

Fix the broken gif in PoseNet.

---

posenet/src/posenet_model.ts

This fixes the issue that the user specified flipping argument is not used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/245)

fixes a small bug in single-person API

---

posenet/demos/package.json
posenet/demos/yarn.lock
posenet/package.json

Release a new patch version of posenet with this fix: https://github.com/tensorflow/tfjs-models/pull/245
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/251)

Update posenet to 2.1.1

---

posenet/package.json

Fixes https://github.com/tensorflow/tfjs/issues/1720
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/255)

Republish posenet -- update version to 2.1.2

---

posenet/README.md

Add missing `modelUrl` param to README.md.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/256)

Add missing `modelUrl` param to README

---

posenet/src/types.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/257)

Add declare to the types for PoseNet so they don't get rewritten by closure.

---

body-pix/rollup.config.js
coco-ssd/rollup.config.js
knn-classifier/rollup.config.js
mobilenet/rollup.config.js
posenet/rollup.config.js
posenet/src/resnet.ts
toxicity/rollup.config.js
universal-sentence-encoder/rollup.config.js

Also add the license to the preamble for all the models.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/258)

Add license to resnet.ts in posenet.

---

posenet/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/259)

Update PoseNet to 2.1.3

---

posenet/demos/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/276)

Fix broken images in posenet demos.

---

body-pix/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/277)

Update body pix to 1.1.2.

---

mobilenet/README.md
mobilenet/src/index.ts

Fixes: https://github.com/tensorflow/tfjs/issues/1830
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/283)

fix normalization constant

---

mobilenet/package.json

This includes the fix: tensorflow/tfjs#1830
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/286)

Update mobilenet to 2.0.4

---

knn-classifier/src/index.ts
knn-classifier/src/index_test.ts
package.json
yarn.lock

Closes https://github.com/tensorflow/tfjs/issues/1498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/298)

[knn-classifier] Fix clearClass to not leak tensor

---

toxicity/demo/package.json
toxicity/demo/yarn.lock
toxicity/package.json
toxicity/yarn.lock
universal-sentence-encoder/demo/package.json
universal-sentence-encoder/demo/yarn.lock
universal-sentence-encoder/package.json
universal-sentence-encoder/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/300)

Bump toxicity and USE dependencies and version numbers. 

---

posenet/src/index.ts

exporting some types of posenet, as well as a  utility methods, to make it more consumable in parts and from typescript.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/285)

exporting more of posenet

---

body-pix/demos/yarn.lock

Resolves security warning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/303)

body-pic demo update parcel bundler in yarn.lock

---

body-pix/README.md
body-pix/demos/index.js
body-pix/src/body_pix_model.ts
body-pix/src/body_pix_test.ts
body-pix/src/output_rendering_util.ts

The four methods look like:
- segment(Multi)Person
- segment(Multi)PersonParts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/305)

Rename bodypix methods to shorter names.

---

body-pix/README.md

This PR contains README updates for the BodyPix 2.0 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/304)

Updates BodyPix 2.0 README.md

---

body-pix/README.md
body-pix/src/body_pix_model.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/322)

Fix bug in segmentMultiPersonParts not reading from config right.

---

body-pix/src/output_rendering_util.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/323)

[BodyPix] Support resized images for rendering utilities.

---

coco-ssd/demo/package.json
coco-ssd/demo/yarn.lock
knn-classifier/demo/package.json
knn-classifier/demo/yarn.lock
knn-classifier/package.json
knn-classifier/yarn.lock
posenet/demos/package.json
posenet/demos/yarn.lock
speech-commands/demo/package.json
speech-commands/demo/yarn.lock
speech-commands/package.json
speech-commands/yarn.lock
toxicity/demo/package.json
toxicity/demo/yarn.lock
universal-sentence-encoder/demo/package.json
universal-sentence-encoder/demo/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/325)

Fix security warnings.

---

knn-classifier/demo/index.html
knn-classifier/demo/index.js
knn-classifier/yarn.lock

Fixes https://github.com/tensorflow/tfjs/issues/2157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/326)

Fix the KNN classifier demo to work with out of order classes.

---

body-pix/README-v2.md
body-pix/README.md

There have been a few people confused (e.g. this fixes https://github.com/tensorflow/tfjs/issues/2195) by the fact that we updated the README but haven't yet released the new package.
Moving this to a separate markdown file until we're ready to release and reverting the main README to the v1 readme.
Other confusions:
https://github.com/tensorflow/tfjs/issues/2240
https://github.com/tensorflow/tfjs/issues/2227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/327)

[BodyPix] Move README.md to README-v2.md to not confuse users.

---

knn-classifier/package.json
knn-classifier/yarn.lock
speech-commands/package.json
speech-commands/yarn.lock

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/328)

Bring knn-classifier and speech-commands TS version to 3.5.3.

---

.gitignore
cloudbuild.yml
package.json
presubmit.ts
scripts/diff.js
scripts/test-util.js

These are taken from our monorepo.
We copy paste the files because sharing code is too complex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/329)

Check in a script that diffs each folder against master.

---

body-pix/cloudbuild.yml
body-pix/karma.conf.js
body-pix/package.json
body-pix/src/body_pix_test.ts
body-pix/src/setup_test.ts
body-pix/yarn.lock

This does not change any existing tests just runs the existing ones on browserstack instead of in node.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/332)

Run tests on browserstack for body pix.

---

speech-commands/src/browser_fft_recognizer.ts
speech-commands/src/browser_fft_recognizer_test.ts

BUG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/336)

[speech-commands] Fix memory leak in the recognize() method

---

speech-commands/demo/package.json
speech-commands/demo/yarn.lock
speech-commands/package.json
speech-commands/src/version.ts
speech-commands/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/337)

[speech-commands] Bump version to 0.4.0; Depend on tfjs 1.3.0

---

posenet/demos/package.json
posenet/demos/yarn.lock

1.3.1 was released with the fix!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/339)

[Posenet] Update the demo to latest versions.

---

deeplab/.npmignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/344)

[deeplab] add npmignore

---

deeplab/demo/package.json
deeplab/demo/yarn.lock
deeplab/yarn.lock

to depend on published package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/345)

update demo package.json

---

body-pix/README-v2.md
body-pix/demos/index.js
body-pix/src/body_pix_model.ts
body-pix/src/output_rendering_util.ts
body-pix/src/types.ts

Update segmentPerson() and segmentPersonParts() methods to return poses of all people in the image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/347)

Returns all poses in segmentPerson() and segmentPersonParts().

---

body-pix/package.json

This release includes the following fix:
https://github.com/tensorflow/tfjs-models/commit/bc65a4b5980d00a3acaba6fdf621be91953cba9f
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/352)

update BodyPix version to 2.0.1

---

body-pix/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/355)

fixes a minor format error in README

---

body-pix/demos/package.json
body-pix/demos/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/356)

Updates demo to use the latest bodypix 2.0.2

---

body-pix/demos/index.html

Updates the description on the demo page html to reflect new updates from BodyPix 2.0
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/359)

updates the description on the demo page

---

coco-ssd/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/361)

Update README.md for optimization using the latest converter

---

body-pix/src/util.ts

Grab min and max from constants
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/365)

BodyPix - fix internal resolution message

---

scripts/publish-npm.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/370)

Remove for-publish in build-npm

---

coco-ssd/yarn.lock
knn-classifier/yarn.lock
mobilenet/yarn.lock
posenet/yarn.lock
toxicity/yarn.lock
universal-sentence-encoder/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/371)

Update lock files.

---

blazeface/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/389)

[blazeface] Add mediapipe link to docs.

---

blazeface/demo/index.html

The demo appears to freeze on iPhones because the video stream is static. If I remove `display:none` from the video and hide it with `visibility:hidden` instead, the demo works.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/390)

[blazeface] Fix demo for iPhone.

---

blazeface/demo/yarn.lock
blazeface/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/393)

[blazeface] Updated demo yarn and version files after publishing.

---

qna/.npmignore
qna/package.json
qna/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/403)

add npm ignore file and updated the npm version

---

qna/README.md
qna/package.json
qna/src/bert_tokenizer.ts
qna/src/mobile_bert.ts
qna/src/mobile_bert_test.ts
qna/src/version.ts
qna/yarn.lock

fix https://github.com/tensorflow/tfjs/issues/2730
https://tfhub.dev/tensorflow/mobilebert/1
The vocal file is also migrated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/404)

use tfhub model url for loading and updated the version

---

qna/demo/index.html
qna/demo/package.json
qna/demo/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/406)

update the qna demo to latest version

---

speech-commands/demo/package.json
speech-commands/demo/yarn.lock
speech-commands/package.json
speech-commands/src/browser_fft_recognizer.ts
speech-commands/src/version.ts
speech-commands/yarn.lock

- Version: 0.4.1 --> 0.4.2
- Dependencies: tfjs and tfjs-node --> 1.5.2
TESTED:
- Manually verified that demo works (inference and transfer learning)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/405)

[speech-commands] Upgrade version and dependencies

---

blazeface/demo/index.js
blazeface/demo/package.json
blazeface/demo/yarn.lock
blazeface/package.json
blazeface/src/face.ts
blazeface/src/version.ts

- Update demo source to use latest WASM build (I've already published the updated demo on GCP)
- Fix flipFaceHorizontal function to initialize `flipped` to an empty object so it's possible to assign properties to it. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/408)

[blazeface] Fix flipHorizontal mode, update demo to use latest wasm build.

---

qna/demo/index.js
qna/demo/package.json
qna/package.json
qna/src/index.ts
qna/src/question_an_answer_test.ts
qna/src/question_and_answer.ts
qna/src/version.ts

update the version file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/411)

qna 1.0 version

---

qna/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/417)

[QnA] Fix links in README.md

---

handpose/demo/package.json
handpose/demo/yarn.lock
handpose/package.json
handpose/src/version.ts
handpose/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/420)

[handpose] Update dependencies.

---

body-pix/src/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/422)

Export bodypix types so it can be used in tests in google3.

---

body-pix/package.json
body-pix/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/423)

Update bodypix version to 2.0.5.

---

body-pix/src/part_channels.ts
body-pix/src/types.ts
body-pix/src/util.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/424)

[BodyPix] Add licenses to missing files.

---

body-pix/src/body_pix_model.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/425)

[BodyPix] Fix closure errors.

---

handpose/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/428)

[handpose] Update README.

---

blazeface/README.md
body-pix/README-v1.md
body-pix/README.md
coco-ssd/README.md
deeplab/README.md
facemesh/README.md
facemesh/demo/README.md
handpose/README.md
handpose/demo/README.md
knn-classifier/README.md
mobilenet/README.md
posenet/README.md
qna/README.md
speech-commands/README.md
toxicity/README.md
universal-sentence-encoder/README.md

Fix typos and use vanilla syntax for importing modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/429)

Improve README's.

---

facemesh/demo/README.md

Folder name is "demo"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/431)

Fixed typos in facemesh demo

---

coco-ssd/demo/package.json
coco-ssd/demo/yarn.lock
coco-ssd/package.json
coco-ssd/src/index.ts
coco-ssd/src/version.ts

this fixes the error raised here
https://stackoverflow.com/questions/61036180/tensorflowjs-tfjs-error-the-dtype-of-dict
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/433)

fix coco-ssd warmup run dtype error

---

blazeface/package.json
blazeface/yarn.lock
body-pix/yarn.lock
coco-ssd/package.json
coco-ssd/yarn.lock
deeplab/yarn.lock
facemesh/package.json
facemesh/yarn.lock
handpose/package.json
handpose/yarn.lock
knn-classifier/yarn.lock
mobilenet/package.json
mobilenet/yarn.lock
posenet/package.json
posenet/yarn.lock
qna/package.json
qna/yarn.lock
speech-commands/yarn.lock
toxicity/package.json
toxicity/yarn.lock
universal-sentence-encoder/package.json
universal-sentence-encoder/yarn.lock
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/436)

Bump dev deps version to remove security vulnerability

---

handpose/demo/index.js
handpose/demo/package.json
handpose/src/pipeline.ts
handpose/src/rotate_webgpu.ts

Rotate op is required in handpose when running in webgpu backend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/427)

[handpose] Add rotate op

---

cloudbuild.yml
facemesh/cloudbuild.yml
facemesh/src/index.ts
facemesh/yarn.lock
handpose/demo/index.js
handpose/package.json
handpose/src/pipeline.ts
handpose/src/rotate_webgpu.ts
handpose/yarn.lock

Should address this issue https://github.com/tensorflow/tfjs/issues/2906
What do you think @annxingyuan. Also if this looks good to you are version bumps done via scripts or directly in the PR making the change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/446)

allow handpose to execute on react native and tensorflow backends

---

handpose/demo/package.json
handpose/demo/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/448)

update handpose demo

---

facemesh/package.json
facemesh/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/450)

[facemesh] Update version.

---

body-pix/README.md

fixes https://github.com/tensorflow/tfjs/issues/3347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/453)

Update bodypix README.md

---

facemesh/README.md
handpose/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/454)

[facemesh / handpose] Update README to require union package.

---

blazeface/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/455)

[blazeface] Update readme.

---

handpose/demo/index.js
handpose/demo/package.json
handpose/demo/yarn.lock
handpose/package.json
handpose/src/rotate_cpu.ts
handpose/src/version.ts
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/458)

[handpose] Fix CPU rotation kernel. 

---

posenet/README.md
posenet/src/posenet_model.ts

This fixes https://github.com/tensorflow/tfjs/issues/3394
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/459)

[posenet] Update docs.

---

coco-ssd/demo/index.html
coco-ssd/demo/index.js
coco-ssd/demo/package.json
coco-ssd/demo/yarn.lock
coco-ssd/package.json
coco-ssd/rollup.config.js
coco-ssd/run_tests.ts
coco-ssd/src/ssd_test.ts
coco-ssd/src/version.ts
coco-ssd/tsconfig.test.json
coco-ssd/yarn.lock
package.json
tsconfig.json
tsconfig.test.json
yarn.lock

fix https://github.com/tensorflow/tfjs/issues/3485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/462)

align coco-ssd with 2.0.1 releases

---

handpose/demo/index.js

When I ran the program, it said "tf is not defined", it's because the update deleted it by mistake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/456)

some mistake caused by delete

---

speech-commands/training/browser-fft/README.md
speech-commands/training/soft-fft/README.md

/cc @khanhlvg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/489)

speech-commands/training: fix model links

---

universal-sentence-encoder/package.json
universal-sentence-encoder/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/499)

fix npm loading for USE model

---

universal-sentence-encoder/README.md

This is to fix image loading error on NPM website for USE package.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/503)

use the gcp for image storage for USE readme file.

---

universal-sentence-encoder/package.json
universal-sentence-encoder/src/version.ts

USE version updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/504)

update the version for the README change

---

body-pix/src/util.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/511)

[bodypix] Fix lint issues.

---

blazeface/src/face.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/519)

[blazeface] Upstream closure fix (declare JSON interface type).

---

speech-commands/.npmignore

closes https://github.com/tensorflow/tfjs/issues/3434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/524)

Publish sourcemaps for speech commands

---

universal-sentence-encoder/README.md
universal-sentence-encoder/demo/index.js
universal-sentence-encoder/demo/package.json
universal-sentence-encoder/demo/yarn.lock

fix issues https://github.com/tensorflow/tfjs/issues/3996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/527)

udpated the doc and demo for inconsistency

---

face-landmarks-detection/package.json
face-landmarks-detection/src/index.ts
face-landmarks-detection/src/mediapipe-facemesh/index.ts
face-landmarks-detection/src/mediapipe-facemesh/mediapipe-facemesh_test.ts
face-landmarks-detection/src/types.ts
face-landmarks-detection/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/528)

[face-landmarks-detection] Make types extensible.

---

handpose/src/hand.ts
handpose/src/index.ts
handpose/src/pipeline.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/532)

[handpose] Upstream closure fixes.

---

posenet/.npmignore

Make Yalc to push source map files to local repository
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/536)

Publish sourcemap for posenet

---

face-landmarks-detection/demo/index.js

Fix point cloud demo irises colors when there is more than one face
I'm not sure if this is the best solution, but it's very simple.
Thanks
Before
After
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/533)

fix pt cloud irises colors when more than 1 face

---

README.md
handpose/demo/index.js

Have added provision for SIMD in the handpose demo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/539)

Added SIMD for handpose demo, added Handpose and Blazeface to README

---

blazeface/package.json
blazeface/src/face.ts
blazeface/src/version.ts
blazeface/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/548)

Remove chained op usage

---

blazeface/package.json
blazeface/run_tests.ts
blazeface/yarn.lock
cloudbuild.yml

blazeface's tests weren't being triggered in CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/553)

run blazeface tests in ci

---

blazeface/demo/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/555)

Update blazeface demo.

---

coco-ssd/demo/README.md
coco-ssd/demo/index.js
coco-ssd/demo/package.json
coco-ssd/demo/yarn.lock
coco-ssd/package.json
coco-ssd/src/index.ts
coco-ssd/src/version.ts
coco-ssd/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/564)

Upgrade coco-ssd to 3.0.0-rc.1

---

posenet/demos/camera.js
posenet/demos/coco.js
posenet/demos/demo_util.js
posenet/demos/package.json
posenet/demos/yarn.lock
posenet/package.json
posenet/run_tests.ts
posenet/src/base_model.ts
posenet/src/mobilenet.ts
posenet/src/posenet_test.ts
posenet/src/resnet.ts
posenet/src/single_pose/argmax2d.ts
posenet/src/single_pose/util.ts
posenet/src/util.ts
posenet/yarn.lock

Fixes https://github.com/tensorflow/tfjs/issues/4552
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/570)

Upgrade posenet to 3.0.0-rc.1

---

blazeface/demo/package.json
blazeface/demo/yarn.lock
blazeface/package.json
blazeface/yarn.lock

Fixed https://github.com/tensorflow/tfjs/issues/4544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/574)

Upgrade blazeface to 3.0.0-rc.1

---

universal-sentence-encoder/demo/README.md
universal-sentence-encoder/demo/index.html
universal-sentence-encoder/demo/index.js
universal-sentence-encoder/demo/package.json
universal-sentence-encoder/demo/yarn.lock
universal-sentence-encoder/package.json
universal-sentence-encoder/src/index.ts
universal-sentence-encoder/yarn.lock

PS, the extra "loadTokenizer" export in index.ts is needed in the toxiticy model. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/573)

Upgrade universal-sentence-encoder to 3.0.0-rc.1

---

deeplab/demo/package.json
deeplab/demo/yarn.lock
deeplab/package.json
deeplab/src/version.ts
deeplab/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/577)

update deeplab to tfjs 3.0.0

---

speech-commands/training/browser-fft/training_custom_audio_model_in_python.ipynb

Notebook is currently invalid JSON.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/580)

Escape newline to fix JSON

---

README.md
handpose/demo/package.json
handpose/demo/yarn.lock
handpose/package.json
handpose/src/version.ts
handpose/yarn.lock

Fixed https://github.com/tensorflow/tfjs/issues/4654
Upgrade handpose to 3.0.0 and update version to 0.0.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/583)

upgrade handpose to 3.0 and udpate the link in README

---

blazeface/demo/index.js
blazeface/demo/package.json
blazeface/demo/yarn.lock
blazeface/package.json
blazeface/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/586)

Update tfjs to 3.1.0

---

blazeface/src/version.ts
face-landmarks-detection/demo/package.json
face-landmarks-detection/demo/yarn.lock
face-landmarks-detection/package.json
face-landmarks-detection/src/index.ts
face-landmarks-detection/src/mediapipe-facemesh/index.ts
face-landmarks-detection/src/mediapipe-facemesh/pipeline.ts
face-landmarks-detection/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/569)

Upgrade face-landmark-detection to 3.0.0-rc.1

---

face-landmarks-detection/demo/package.json
face-landmarks-detection/demo/yarn.lock
face-landmarks-detection/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/587)

Update face-landmarks-detection dependency to tfjs 3.1.0

---

mobilenet/demo/package.json
mobilenet/demo/yarn.lock
mobilenet/package.json
mobilenet/src/version.ts
mobilenet/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/590)

update mobilenet to dep on tfjs 3.1

---

speech-commands/package.json
speech-commands/rollup.config.js
speech-commands/src/version.ts

fixed https://github.com/tensorflow/tfjs/issues/4719
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/598)

set the correct name space for tfjs-data in rollup

---

pose-detection/src/index.ts
pose-detection/src/pose_detector.ts
pose-detection/src/posenet/detector.ts
pose-detection/src/posenet/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/608)

Initial checkin of posenet.

---

speech-commands/package.json
speech-commands/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/613)

[speech-commands]Update to 0.5.4

---

pose-detection/demo/.babelrc
pose-detection/demo/index.html
pose-detection/demo/index.js
pose-detection/demo/package.json
pose-detection/demo/yarn.lock
pose-detection/rollup.config.js
pose-detection/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/614)

[pose-detection]Setup demo.

---

handpose/README.md

I noticed that current demo path doesn't exists so I changed it according to the link seen in the main README file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/609)

[handpose] Update demo link in README

---

pose-detection/demo/src/camera.js
pose-detection/demo/yarn.lock
pose-detection/src/blazepose/blazepose_test.ts
pose-detection/src/blazepose/calculators/visibility_smoothing.ts
pose-detection/src/blazepose/detector.ts
pose-detection/yarn.lock

Remove early returns in the pipeline, let result propagate through pipeline in order for downstream filters to have a chance to reset states if detections is empty or landmarks is empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/622)

[pose-detection]Refactor pipeline.

---

pose-detection/src/blazepose/calculators/tensors_to_landmarks.ts
pose-detection/src/blazepose/calculators/visibility_smoothing.ts
pose-detection/src/types.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/624)

[pose-detection]Change visibility to score.

---

pose-detection/demo/src/camera.js
pose-detection/demo/src/index.js
pose-detection/demo/src/option_panel.js
pose-detection/demo/src/params.js
pose-detection/src/blazepose/calculators/tensors_to_landmarks.ts

1. Fix a bug in the sigmoid function that calculates visibility score.
2. Add score threshold to demo UI.
3. Fix demo to not render result when model is changing.
4. Change how we count FPS, only time the duration for calling estimatePoses.
Screenshot of the Demo UI:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/623)

[pose-detection] Add visibility parameter to demo UI.

---

pose-detection/src/posenet/detector.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/626)

Fix constructor call.

---

pose-detection/demo/src/camera.js
pose-detection/src/blazepose/calculators/interfaces/common_interfaces.ts
pose-detection/src/blazepose/calculators/interfaces/config_interfaces.ts
pose-detection/src/blazepose/calculators/landmarks_one_euro_filter.ts
pose-detection/src/blazepose/calculators/landmarks_smoothing.ts
pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts
pose-detection/src/blazepose/calculators/visibility_smoothing.ts
pose-detection/src/blazepose/constants.ts
pose-detection/src/blazepose/detector.ts
pose-detection/src/calculators/constants.ts
pose-detection/src/calculators/interfaces/config_interfaces.ts
pose-detection/src/calculators/landmarks_to_normalized_landmarks.ts
pose-detection/src/calculators/low_pass_filter.ts
pose-detection/src/calculators/normalized_landmarks_to_landmarks.ts
pose-detection/src/calculators/one_euro_filter.ts
pose-detection/src/calculators/relative_velocity_filter.ts
pose-detection/src/calculators/velocity_filter_utils.ts

1. Add relative velocity filter.
2. Add one euro filter.
3. Add landmark filter that uses velocity filter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/625)

[pose-detection]Add landmark filter.

---

pose-detection/demo/src/camera.js
pose-detection/demo/src/params.js
pose-detection/src/calculators/interfaces/common_interfaces.ts
pose-detection/src/calculators/landmarks_to_normalized_landmarks.ts
pose-detection/src/constants.ts
pose-detection/src/index.ts
pose-detection/src/util.ts

This PR improves the demo by using different colors for different sides:
White for middle (Nose).
Green for left.
Orange for right.
Also fixed a circular dependency bug in two files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/629)

[pose-detection]Add color to demo.

---

cloudbuild.yml
pose-detection/cloudbuild.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/633)

Add pose-detection to CI test.

---

pose-detection/package.json
pose-detection/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/634)

[pose-detection]Prepare release version 0.0.1-rc.0

---

pose-detection/demo/package.json
pose-detection/demo/src/camera.js
pose-detection/demo/src/index.js
pose-detection/demo/src/option_panel.js
pose-detection/demo/src/params.js
pose-detection/demo/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/635)

[pose-detection]Update demo.

---

pose-detection/src/blazepose/calculators/landmarks_smoothing.ts
pose-detection/src/blazepose/calculators/visibility_smoothing.ts
pose-detection/src/blazepose/detector.ts
pose-detection/src/calculators/one_euro_filter.ts
pose-detection/src/calculators/relative_velocity_filter.ts
pose-detection/src/movenet/detector.ts
pose-detection/src/posenet/calculators/flip_poses.ts
pose-detection/src/posenet/calculators/scale_poses.ts
pose-detection/src/posenet/detector.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/640)

[pose-detection]Fix lint to be consistent with g3 rules.

---

pose-detection/src/blazepose/detector.ts
pose-detection/src/create_detector.ts
pose-detection/src/movenet/detector.ts
pose-detection/src/pose_detector.ts
pose-detection/src/posenet/detector.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/642)

[pose-detection]Allow detector to reset to clear global states.

---

pose-detection/src/movenet/constants.ts
pose-detection/src/movenet/detector.ts
pose-detection/src/movenet/detector_utils.ts
pose-detection/src/movenet/types.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/641)

[pose-detection] Add MoveNet keypoint smoothing parameter

---

pose-detection/demo/package.json
pose-detection/demo/yarn.lock
pose-detection/package.json
pose-detection/src/posenet/posenet_test.ts
pose-detection/src/version.ts
pose-detection/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/647)

[pose-detection]Update to version 0.0.1-rc.1

---

pose-detection/src/calculators/one_euro_filter_test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/646)

Add test for one-euro filter

---

pose-detection/src/calculators/one_euro_filter_test.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/650)

[pose-detection]Fix test.

---

pose-detection/src/movenet/detector.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/654)

[pose-detection] MoveNet returns pose score and keypoint names

---

pose-detection/demo/src/option_panel.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/657)

[pose-detection]Refactor code.

---

pose-detection/src/constants.ts
pose-detection/src/movenet/detector.ts
pose-detection/src/util.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/659)

[pose-detection]Add named output util.

---

pose-detection/demo/src/camera.js
pose-detection/demo/src/index.js
pose-detection/demo/src/option_panel.js
pose-detection/demo/src/params.js

In previous https://github.com/tensorflow/tfjs-models/pull/656, we use url to control which model to load and eliminate other models from showing in the UI. In this PR, we add back other model selection so that user can easily switch models for comparison. Initial loading is still controlled by url query string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/660)

[pose-detection]Add model comparison to demo.

---

pose-detection/demo/index.html
pose-detection/demo/package.json
pose-detection/demo/src/index.js
pose-detection/demo/src/option_panel.js
pose-detection/demo/src/params.js
pose-detection/demo/src/util.js
pose-detection/demo/yarn.lock
pose-detection/yarn.lock

This PR adds backend options (similar to our benchmark tool) to the demo, so that it allows us to easily switch optimization flags and test the result with real video.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/663)

[pose-detection]Add backend options to demo.

---

pose-detection/demo/index.html
pose-detection/demo/package.json
pose-detection/demo/src/camera.js
pose-detection/demo/src/index.js
pose-detection/demo/src/option_panel.js
pose-detection/demo/src/params.js
pose-detection/demo/src/util.js
pose-detection/demo/yarn.lock
pose-detection/package.json
pose-detection/yarn.lock

There are two issues:
1. Sometimes the loadeddata is not ready when inference, so added code make sure to always wait for data is ready.
2. Large canvas rendering will freeze iPhone Safari, so added code to default to a smaller size if mobile devices. Also added the size option so that desktop can test it too.
Also add below fixes:
1. Update to use tfjs 3.5.0
2. Fix backend change logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/665)

[pose-detection] Fix demo iPhone issue.

---

pose-detection/demo/src/camera.js
pose-detection/demo/src/index.js
pose-detection/demo/src/option_panel.js
pose-detection/demo/src/params.js
pose-detection/demo/yarn.lock
pose-detection/src/posenet/calculators/build_part_with_score_queue.ts
pose-detection/src/posenet/calculators/decode_multiple_poses.ts
pose-detection/src/posenet/calculators/decode_multiple_poses_util.ts
pose-detection/src/posenet/calculators/max_heap.ts
pose-detection/src/posenet/constants.ts
pose-detection/src/posenet/detector.ts
pose-detection/src/posenet/posenet_test.ts
pose-detection/src/posenet/types.ts
pose-detection/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/667)

[pose-detection]Add multi pose prediction to PoseNet

---

pose-detection/src/blazepose/detector.ts
pose-detection/yarn.lock

Given that we have the reset function, we can have early return in the code. This will simplify null check in every function everywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/670)

[pose-detection]Refactor blazepose pipeline.

---

pose-detection/src/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/669)

[pose-detection]Expose normalize keypoint method.

---

pose-detection/demo/src/option_panel.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/676)

[pose-detection]Default to lightning model for MoveNet demo.

---

pose-detection/demo/index.html
pose-detection/demo/src/stats_panel.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/677)

[pose-detection]Make FPS panel bigger.

---

pose-detection/README.md

This is a shared README for the pose-detection API. Model specific README should in their own folders.
See how it looks here: https://github.com/tensorflow/tfjs-models/blob/961d9294ab8c14f8c859fd86407f9508e3daccae/pose-detection/README.md
Note: This is the README that users will see when they enter the pose-detection page on GitHub. It provides general information about usage, provide demo links and showcase some animated GIFs (to add). In the future, we can add a gallery, which showcase applications created using this API.
The following information should go into the README in each model's folder: (1) Model specific usage such as configs (2) Model specific information such as model description (3) Other demo links, gallery, etc.
---
This change is [<img …

[pose-detection] Add README

---

pose-detection/demo/package.json
pose-detection/demo/yarn.lock
pose-detection/package.json
pose-detection/src/movenet/constants.ts
pose-detection/src/version.ts
pose-detection/yarn.lock

1. Update MoveNet model to v3.
2. Update tfjs dependency to 3.6.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/681)

[pose-detection]Update to 0.0.1-rc.2

---

speech-commands/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/684)

Fixing broken like for speech commands datasets

---

pose-detection/demos/live_video/src/index.js
pose-detection/demos/live_video/src/stats_panel.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/685)

[pose-detection] Update fps calculation in live demo

---

pose-detection/demos/live_video/src/index.js
pose-detection/demos/live_video/src/option_panel.js

Fixed demo bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/687)

[pose-detection]Fix demo bug when backend switch.

---

pose-detection/src/movenet/detector.ts
speech-commands/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/686)

[pose-detection] Prevent simultaneous calls to MoveNet's estimatePoses

---

pose-detection/src/movenet/detector.ts

Reverts tensorflow/tfjs-models#686
Causes issues with pose detection results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/689)

Revert "[pose-detection] Prevent simultaneous calls to MoveNet's estimatePoses"

---

pose-detection/src/movenet/detector.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/692)

[pose-detection] Use synchronous MoveNet tensor download when possible

---

body-pix/demo/.babelrc
body-pix/demo/package.json
body-pix/demo/yarn.lock
body-pix/package.json
body-pix/src/body_pix_test.ts
body-pix/src/version.ts
body-pix/yarn.lock
pose-detection/demos/live_video/package.json
pose-detection/demos/live_video/yarn.lock
pose-detection/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/693)

Update body-pix version

---

pose-detection/README.md
pose-detection/src/constants.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/698)

[pose-detection]Flip blazepose left/right.

---

pose-detection/src/calculators/relative_velocity_filter_test.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/697)

[pose-detection]Add filter test.

---

pose-detection/README.md
pose-detection/demos/live_video/src/index.js
pose-detection/demos/live_video/src/option_panel.js
pose-detection/demos/upload_video/src/index.js
pose-detection/demos/upload_video/src/option_panel.js
pose-detection/src/blazepose/blazepose_test.ts
pose-detection/src/blazepose/detector.ts
pose-detection/src/blazepose/detector_utils.ts
pose-detection/src/blazepose/index.ts
pose-detection/src/blazepose/types.ts
pose-detection/src/create_detector.ts
pose-detection/src/index.ts
pose-detection/src/pose_detector.ts
pose-detection/src/types.ts
pose-detection/src/util.ts

Refactor naming to be consistent.
For README, doccomment, change to MediaPipe BlazePose.
For variables, change to blazepose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/700)

[pose-detection]Refactor MediaPipe BlazePose naming in code base.

---

pose-detection/demos/live_video/package.json
pose-detection/demos/live_video/src/index.js
pose-detection/demos/live_video/yarn.lock
pose-detection/src/blazepose/blazepose_test.ts
pose-detection/src/blazepose/calculators/interfaces/config_interfaces.ts
pose-detection/src/blazepose/calculators/refine_landmarks_from_heatmap.ts
pose-detection/src/blazepose/calculators/refine_landmarks_from_heatmap_test.ts
pose-detection/src/blazepose/calculators/tensors_to_landmarks.ts
pose-detection/src/blazepose/constants.ts
pose-detection/src/blazepose/detector.ts
pose-detection/src/blazepose/detector_utils.ts
pose-detection/src/calculators/sigmoid.ts
pose-detection/yarn.lock

1. Switch to new detector and landmark full model.
2. Add refineLandmarksFromHeatmap calculator and tests.
3. Update tf.js dependency to 3.6.0.
4. Update pipeline configs, mainly changing resolution from 128x128 to 224x224. Change anchor from 4 layers to 5 layers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/694)

[pose-detection]Add heatmap.

---

pose-detection/src/blazepose_mediapipe/detector.ts
pose-detection/src/blazepose_mediapipe/mediapipe_test.ts
pose-detection/src/blazepose_mediapipe/types.ts
pose-detection/src/blazepose_tfjs/constants.ts
pose-detection/src/blazepose_tfjs/detector.ts
pose-detection/src/blazepose_tfjs/detector_utils.ts
pose-detection/src/create_detector.ts
pose-detection/src/index.ts

This PR adds model type (possible value: lite|full|heavy) to BlazePose. Also disabled static image test because there's a bug that needs to be fixed in @mediapipe/pose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/703)

[pose-detection]Add model type to BlazePose.

---

pose-detection/src/blazepose_tfjs/blazepose_test.ts
pose-detection/src/blazepose_tfjs/constants.ts
pose-detection/src/blazepose_tfjs/detector.ts

Bundle size is reduced by half.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/708)

[pose-detection]Use f16 model.

---

pose-detection/demos/live_video/src/index.js
pose-detection/demos/live_video/src/option_panel.js

Enable user to choose between lite, full and heavy model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/709)

[pose-detection]Add type to BlazePose demo.

---

pose-detection/demos/upload_video/src/camera.js
pose-detection/src/blazepose_mediapipe/mediapipe_test.ts
pose-detection/src/blazepose_mediapipe/types.ts
pose-detection/src/blazepose_tfjs/blazepose_test.ts
pose-detection/src/create_detector.ts
pose-detection/src/posenet/detector.ts

For initial launch, don't set default for BlazePose. Depending on MP solution improvement and user feedback, we may set a default at a later time.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/716)

[pose-detection]Not set default for BlazePose.

---

pose-detection/src/blazepose_mediapipe/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/717)

Add README.md to blazepose_mediapipe.

---

pose-detection/src/blazepose_mediapipe/README.md
pose-detection/src/blazepose_tfjs/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/720)

[pose-detection]Add README.md to BlazePoseTfjs

---

pose-detection/src/posenet/calculators/decode_multiple_poses.ts
pose-detection/src/posenet/constants.ts
pose-detection/src/posenet/detector.ts

Multi-person was broken because name change, e.g. rightEye changed to right_eye in COCO_KEYPOINTS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/721)

[pose-detection]Fix PoseNet multi person bug.

---

pose-detection/demos/live_video/package.json
pose-detection/demos/live_video/src/index.js

This reduces files to upload to our cloud storage, also expedite wasm file download time because jsdelivr compress wasm files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/722)

[pose-detection]Load wasm files from jsdelivr.

---

pose-detection/demos/upload_video/package.json
pose-detection/demos/upload_video/src/index.js
pose-detection/demos/upload_video/src/option_panel.js
pose-detection/demos/upload_video/src/params.js
pose-detection/demos/upload_video/src/stats_panel.js
pose-detection/demos/upload_video/src/util.js
pose-detection/demos/upload_video/yarn.lock
pose-detection/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/725)

Update upload video demo

---

pose-detection/package.json
pose-detection/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/724)

[pose-detection]Release 0.0.1

---

pose-detection/README.md
pose-detection/demos/README.md
pose-detection/demos/live_video/yarn.lock
pose-detection/demos/upload_video/yarn.lock
pose-detection/src/blazepose_mediapipe/README.md
pose-detection/src/blazepose_tfjs/README.md
pose-detection/src/blazepose_tfjs/types.ts
pose-detection/src/movenet/README.md
pose-detection/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/728)

[pose-detection]Update readme

---

pose-detection/src/posenet/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/730)

[pose-detection]Add README.md to PoseNet

---

pose-detection/rollup.config.js

This PR adds 'Pose' to global namespace, so that bundler work properly. Tested generated bundle with both installing through npm and script tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/731)

[pose-detection]Fix build bug.

---

pose-detection/src/blazepose_mediapipe/README.md
pose-detection/src/blazepose_tfjs/README.md

Cross link the two runtime's README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/733)

[pose-detection]Refine BlazePose README.

---

tasks/README.md
tasks/package.json
tasks/src/tasks/nl_classification/tflite_common.ts
tasks/src/tasks/question_and_answer/bert_qa_tfjs.ts
tasks/src/tasks/sentiment_detection/movie_review_tflite.ts
tasks/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/734)

Update task API version and minor bug fixes.

---

pose-detection/demos/live_video/yarn.lock
pose-detection/src/blazepose_tfjs/calculators/refine_landmarks_from_heatmap.ts
pose-detection/src/blazepose_tfjs/constants.ts
pose-detection/src/blazepose_tfjs/detector.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/739)

[pose-detection]Use tfhub link for BlazePose.

---

pose-detection/src/blazepose_mediapipe/README.md
pose-detection/src/blazepose_tfjs/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/741)

[pose-detection]Add model quality table for BlazePose.

---

pose-detection/package.json
pose-detection/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/742)

[pose-detection]Release 0.0.2

---

pose-detection/.npmignore
pose-detection/package.json
pose-detection/src/version.ts

Exclude assets and demos from npm package to reduce npm package size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/744)

[pose-detection]Release 0.0.3

---

universal-sentence-encoder/package.json
universal-sentence-encoder/src/version.ts
universal-sentence-encoder/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/745)

[use]Upgrade to 1.3.3

---

cloudbuild.yml
tasks/cloudbuild.yml
tasks/package.json
tasks/run_tests.ts
tasks/src/package_loader.ts
tasks/src/task_model.ts
tasks/src/tasks/all_tasks.ts
tasks/src/tasks/all_tasks_test.ts
tasks/src/tasks/common.ts
tasks/src/tasks/object_detection/tflite_common.ts
tasks/src/tasks/question_and_answer/custom_model_tflite.ts
tasks/src/tasks/sentiment_detection/toxicity_tfjs.ts
tasks/tsconfig.test.json
tasks/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/738)

[task] Enable cloudbulid, fix lint errors, and add tests

---

README.md

Add pose API to README's table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/749)

Add pose API to top-level README.

---

pose-detection/package.json
pose-detection/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/761)

[pose-detection]Update pose detection to 0.0.4

---

handpose/demo/.babelrc
handpose/demo/package.json
handpose/demo/yarn.lock

There's a bug in some version of Parcel, pinned it to 1.12.5, same as other packages. Also update dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/765)

[handpose]Fix demo.

---

pose-detection/src/movenet/constants.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/772)

Update constant.ts for MoveNet.

---

pose-detection/demos/live_video/src/index.js
pose-detection/demos/live_video/src/option_panel.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/775)

[pose-detection] Movenet multipose demo

---

pose-detection/src/calculators/interfaces/config_interfaces.ts
pose-detection/src/movenet/constants.ts
pose-detection/src/movenet/detector.ts
pose-detection/src/movenet/detector_utils.ts
pose-detection/src/movenet/types.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/780)

[pose-detection] Allow users to specify the MoveNet tracker configuration

---

pose-detection/src/movenet/detector.ts
pose-detection/src/movenet/detector_utils.ts
pose-detection/src/movenet/types.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/798)

[pose-detection] Allow users to specify multi-pose model input size

---

pose-detection/src/calculators/types.ts
pose-detection/src/index.ts
pose-detection/src/movenet/README.md
pose-detection/src/movenet/detector.ts
pose-detection/src/movenet/detector_utils.ts
pose-detection/src/movenet/types.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/806)

[pose-detection] Move TrackerType enum to calculators directory

---

pose-detection/src/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/807)

[pose-detection] Fix multipose type string

---

pose-detection/demos/live_video/src/camera.js
pose-detection/demos/live_video/src/index.js
pose-detection/demos/live_video/src/option_panel.js
pose-detection/demos/live_video/src/params.js
pose-detection/demos/live_video/yarn.lock

1. Add enableTracker option to demo page. If value is true, it will visualize different person's skeleton with different colors.
2. Fix bugs in modelConfig validation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/802)

[pose-detection]Add tracker option to demo page for MoveNet model.

---

pose-detection/src/movenet/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/811)

[pose-detection] Update benchmarks for multi-pose MoveNet

---

pose-detection/src/movenet/README.md
pose-detection/src/movenet/types.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/812)

[pose-detection] MoveNet documentation

---

pose-detection/demos/live_video/src/option_panel.js
pose-detection/demos/live_video/yarn.lock
pose-detection/yarn.lock

Associate initial tracker state with model type. tracker defaults to on for multipose and off for others.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/810)

[pose-detection]Improve MoveNet demo with tracker on on start.

---

pose-detection/src/movenet/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/815)

[pose-detection] Update MoveNet benchmark results

---

pose-detection/package.json
pose-detection/src/version.ts

Added MoveNet multipose model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/814)

[pose-detection]Update pose detection to 0.0.5

---

pose-detection/src/blazepose_tfjs/constants.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/821)

Update blazepose 3D to tfhub links

---

pose-detection/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/817)

[poes-detection]Update README with MediaPipe 3D information.

---

knn-classifier/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/832)

Delete invalid symbols

---

cloudbuild.yml
hand-detection/cloudbuild.yml
hand-detection/karma.conf.js
hand-detection/package.json
hand-detection/rollup.config.js
hand-detection/run_tests.ts
hand-detection/src/hand_detector.ts
hand-detection/src/setup_test.ts
hand-detection/tsconfig.json
hand-detection/tsconfig.test.json

These files will allow building, running, and testing once hand detection source files are added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/835)

Add building and testing infra to hands detection

---

blazeface/demo/index.js
blazeface/demo/package.json
blazeface/demo/yarn.lock
blazeface/package.json
blazeface/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/851)

[blazeface] Build and serve demo with esbuild

---

hand-pose-detection/src/tfjs/calculators/hand_landmarks_to_rect.ts
hand-pose-detection/src/tfjs/constants.ts
hand-pose-detection/src/tfjs/detector.ts
hand-pose-detection/src/tfjs/detector_utils.ts
hand-pose-detection/src/tfjs/tfjs_test.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/856)

Add lite hands detector model support to TFJS API

---

hand-pose-detection/src/tfjs/calculators/hand_landmarks_to_rect.ts
hand-pose-detection/src/tfjs/detector.ts
pose-detection/src/blazepose_tfjs/detector.ts
shared/calculators/detector_inference.ts
shared/calculators/split_detection_result.ts

Sigmoid was double applied resulting in scores always being greater than the filtering threshold 0.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/857)

Fix detector always accepting all boxes

---

hand-pose-detection/README.md
hand-pose-detection/demos/live_video/package.json
hand-pose-detection/demos/live_video/yarn.lock
hand-pose-detection/demos/upload_video/package.json
hand-pose-detection/demos/upload_video/yarn.lock
hand-pose-detection/package.json
hand-pose-detection/src/mediapipe/README.md
hand-pose-detection/src/mediapipe/detector.ts
hand-pose-detection/src/tfjs/README.md
hand-pose-detection/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/859)

Add 3D keypoints to MediaPipe hand detection

---

hand-pose-detection/README.md
hand-pose-detection/src/tfjs/constants.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/860)

Update to TFHub links for mediapipe hands

---

hand-pose-detection/.npmignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/861)

[hand-pose-detection]Exclude demos from npm package.

---

hand-pose-detection/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/862)

[hand-pose-detection]Format model card link.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/863)

Update model list, remove handpose, add hand-pose-detection

---

shared/calculators/interfaces/common_interfaces.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/864)

Add Mask and Segmentation interface type

---

shared/calculators/mask_util.ts
shared/calculators/mask_util_test.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/866)

Add mask utilities for conversion between mask types

---

coco-ssd/README.md

Glitch link to COCO-SSD demo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/885)

Update to easier to use demo that is live

---

universal-sentence-encoder/README.md
universal-sentence-encoder/demo/index.js
universal-sentence-encoder/demo/package.json
universal-sentence-encoder/demo/yarn.lock

fixed https://github.com/tensorflow/tfjs/issues/5931
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/886)

[use-qna] use tf.matmul for dot product computation

---

pose-detection/src/blazepose_mediapipe/mediapipe_test.ts
pose-detection/src/blazepose_tfjs/blazepose_test.ts
pose-detection/src/blazepose_tfjs/constants.ts
pose-detection/src/blazepose_tfjs/detector.ts
pose-detection/src/blazepose_tfjs/detector_utils.ts
shared/calculators/calculate_inverse_matrix.ts
shared/calculators/calculate_inverse_matrix_test.ts
shared/calculators/calculate_score_copy.ts
shared/calculators/calculate_world_landmark_projection.ts
shared/calculators/convert_image_to_tensor.ts
shared/calculators/get_rotated_sub_rect_to_rect_transformation_matrix.ts
shared/calculators/image_utils.ts
shared/calculators/interfaces/config_interfaces.ts
shared/calculators/segmentation_smoothing.ts
shared/calculators/segmentation_smoothing_test.ts
shared/calculators/tensors_to_segmentation.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/876)

Add pose segmentation output to TFJS BlazePose API

---

body-segmentation/demos/live_video/src/camera.js
body-segmentation/demos/live_video/src/index.js
body-segmentation/demos/live_video/src/option_panel.js
body-segmentation/demos/live_video/yarn.lock
body-segmentation/demos/shared/params.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/914)

Edit camera setting to show all cameras

---

body-segmentation/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/923)

[body-segmentation] Update README to make it up-to-date.

---

body-segmentation/src/selfie_segmentation_tfjs/constants.ts
pose-detection/src/blazepose_tfjs/constants.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/925)

Update segmentation model links to tfhub

---

blazeface/cloudbuild.yml
body-pix/cloudbuild.yml
body-segmentation/cloudbuild.yml
cloudbuild.yml
coco-ssd/cloudbuild.yml
deeplab/cloudbuild.yml
face-landmarks-detection/cloudbuild.yml
hand-pose-detection/cloudbuild.yml
handpose/cloudbuild.yml
knn-classifier/cloudbuild.yml
mobilenet/cloudbuild.yml
pose-detection/cloudbuild.yml
posenet/cloudbuild.yml
qna/cloudbuild.yml
speech-commands/cloudbuild.yml
speech-commands/src/browser_fft_extractor_test.ts
speech-commands/src/browser_fft_recognizer_test.ts
tasks/cloudbuild.yml
toxicity/cloudbuild.yml
universal-sentence-encoder/cloudbuild.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/924)

move node version to 12 to allow security patches

---

body-segmentation/demos/README.md
body-segmentation/demos/live_video/index.html
body-segmentation/demos/live_video/package.json
body-segmentation/demos/live_video/src/index.js
body-segmentation/demos/live_video/src/option_panel.js
body-segmentation/demos/live_video/yarn.lock
body-segmentation/demos/shared/params.js
body-segmentation/demos/shared/stats_panel.js
body-segmentation/demos/upload_video/package.json
body-segmentation/demos/upload_video/src/index.js
body-segmentation/demos/upload_video/src/option_panel.js
body-segmentation/demos/upload_video/yarn.lock
body-segmentation/package.json
body-segmentation/yarn.lock
pose-detection/package.json
pose-detection/src/blazepose_tfjs/blazepose_test.ts
pose-detection/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/921)

Include two FPS counters to track inference as well as end to end FPS

---

body-segmentation/src/selfie_segmentation_tfjs/README.md
body-segmentation/src/selfie_segmentation_tfjs/segmenter.ts
body-segmentation/src/selfie_segmentation_tfjs/types.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/935)

Support passing IOHandler to model urls of selfie_segmentation

---

body-segmentation/.npmignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/936)

Remove images from npm release

---

pose-detection/src/blazepose_tfjs/detector.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/937)

Remove segmentation output from execution when segmentation is disabled

---

pose-detection/package.json
pose-detection/src/blazepose_tfjs/detector.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/938)

Add pose package version

---

pose-detection/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/939)

Add segmmentation output to pose detection README

---

face-detection/src/tfjs/constants.ts
face-landmarks-detection/src/tfjs/constants.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1002)

Update face model links to tfhub

---

depth-estimation/README.md
depth-estimation/package.json
depth-estimation/src/ar_portrait_depth/README.md
depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts
depth-estimation/src/ar_portrait_depth/constants.ts
depth-estimation/src/ar_portrait_depth/estimator.ts
depth-estimation/src/ar_portrait_depth/estimator_utils.ts
depth-estimation/src/ar_portrait_depth/types.ts
depth-estimation/src/types.ts
depth-estimation/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1014)

Move minDepth and maxDepth to estimation config

---

depth-estimation/package.json
depth-estimation/rollup.config.js
depth-estimation/src/version.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1015)

Fix rollup to not include body-segmentation in package

---

face-detection/README.md

Fixes https://github.com/tensorflow/tfjs/issues/6435
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1023)

Fix broken link in face-detection

---

README.md

Modifying number of rows in README.md to fix misalignment in the table
of models. This makes the table more readable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1026)

Modifying number of rows in README.md

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1037)

Add depth estimation to readme

---

speech-commands/README.md

The README has a typo, just fixing it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/956)

Fix a typo

---

body-pix/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1042)

[bodypix] link to body-segmentation

---

pose-detection/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1034)

update @mediapipe/pose from ~0.4.0 to ~0.5.0

---

body-segmentation/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1043)

Fix extra space in link in body-segmentation/README.md

---

face-detection/demos/live_video/package.json
face-detection/demos/live_video/src/index.js
face-detection/demos/live_video/yarn.lock
face-detection/demos/shared/option_panel.js
face-detection/demos/shared/params.js
face-detection/demos/shared/util.js
face-detection/demos/upload_video/package.json
face-detection/demos/upload_video/src/index.js
face-detection/demos/upload_video/yarn.lock
face-detection/package.json
face-detection/yarn.lock
shared/calculators/render_util.ts

1. Add tfjs-webgpu backend and user warnings
2. Update tfjs to 4.0.0
3. Fix backend changing issue in upload_video demo
4. Add URL backend parameter
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1046)

[face-detection] Add WebGPU backend

---

pose-detection/demos/live_video/package.json
pose-detection/demos/live_video/yarn.lock
pose-detection/demos/upload_video/package.json
pose-detection/demos/upload_video/yarn.lock
pose-detection/package.json
pose-detection/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1129)

Update to tfjs 4.2.0 and webgpu 0.0.1-alpha.17 for pose-detection

---

pose-detection/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1139)

Increment pose-detection version to 2.1.0

---

pose-detection/demos/live_video/src/camera.js
pose-detection/demos/live_video/src/index.js
pose-detection/demos/live_video/src/renderer_canvas2d.js
pose-detection/demos/live_video/src/renderer_webgpu.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-models/1138)

Split canvas2d renderer from camera.js

---

face-detection/demos/live_video/package.json
face-detection/demos/live_video/yarn.lock
face-detection/package.json
face-detection/yarn.lock

Update the dependency for face detection model. Aiming to publish new npm release.

Face detection model npm release

---

face-detection/package.json

Update the version number to `1.0.2` to run the npm release script.

Update the face-detection version number

---

face-detection/package.json
face-detection/src/version.ts

Update the version number to 1.0.2

Update version number of face-detection

---

face-landmarks-detection/demos/live_video/package.json
face-landmarks-detection/demos/live_video/yarn.lock
face-landmarks-detection/package.json
face-landmarks-detection/yarn.lock

Update TFJS version of Face Landmarks detection model

---

hand-pose-detection/demos/live_video/package.json
hand-pose-detection/demos/live_video/yarn.lock
hand-pose-detection/package.json
hand-pose-detection/src/tfjs/tfjs_test.ts
hand-pose-detection/yarn.lock

Upgrade hand pose detection

---

body-segmentation/demos/live_video/package.json
body-segmentation/demos/live_video/yarn.lock
body-segmentation/package.json
body-segmentation/src/body_pix/body_pix_test.ts
body-segmentation/src/body_pix/impl/output_rendering_util.ts
body-segmentation/src/body_pix/impl/setup_test.ts
body-segmentation/yarn.lock

Upgrade body segmentation model. Upgrade TFJS version to 4.9.0.

Upgrade body segmentation model

---

blazeface/package.json
face-landmarks-detection/package.json

Update blazeface npm version

---

depth-estimation/package.json
depth-estimation/src/ar_portrait_depth/ar_portrait_depth_test.ts
depth-estimation/yarn.lock

Upgrade TFJS version to 4.10.0 and fix the tests failure.

Update TFJS version

---

qna/demo/package.json
qna/demo/yarn.lock
qna/package.json
qna/yarn.lock

Update qna model TFJS version

---

body-pix/demo/package.json
body-pix/demo/yarn.lock
body-pix/package.json
body-pix/yarn.lock

[Model Update] Update body-pix model

---

pose-detection/rollup.config.js

Fix the issue of https://github.com/tensorflow/tfjs/issues/7930
Will release a new npm package afterwards

[Pose Detection]Fix undefined error
